### ISSUE TITLE
Set is not defined

### ISSUE THREAD

**Issue by brokenseal** [tmpvar/jsdom#1072] opened 2015-03-26 17:27 UTC
Line https://github.com/tmpvar/jsdom/blob/master/lib/jsdom/level2/html.js#L405 uses a variable that is not anywhere, am I the only one getting this?

```
ReferenceError: Set is not defined
    at Object.<anonymous> ([...]node_modules/jsdom/lib/jsdom/level2/html.js:405:28)
```

**Comment by domenic** [comment] 2015-03-26 17:49
Dupe of #1071

**Closed by domenic** 2015-03-26 17:49 UTC
