### ISSUE TITLE
Clarify how to load files from within jsdom

### ISSUE THREAD

**Issue by lukasoppermann** [tmpvar/jsdom#1853] opened 2017-05-15 08:40 UTC
### Basic info:

- **Node.js version:** v7.10.0
- **jsdom version:** v10.1.0

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");
window = (new JSDOM(``, { runScripts: 'dangerously', url: '/' })).window

const scriptEl = window.document.createElement('script')
scriptEl.textContent = requirejs
window.document.head.appendChild(scriptEl)

scriptEl.textContent = `
        window.require = require
        require.config({
          baseUrl: './'
        })
        require(['../../dist/html.sortable.js'], function (sortable) {
          window.requiredSortable = sortable
          window.onModulesLoaded()
        })`
window.document.head.appendChild(scriptEl)
```

### How does similar code behave in browsers?
It loads the file. 😉 

### Problem

I guess I am just doing something wrong. However I did not find enough info on how to load files from within the jsdom to figure out how it works. I am guessing the relative path does not resolve? Please advice.

**Comment by Sebmaster** [comment] 2017-05-15 13:04
The base url you're passing to jsdom is wrong. It needs to be a full url, including the protocol.

**Comment by lukasoppermann** [comment] 2017-05-15 13:07
Oh, damn, so there is no way to include a relative file at all?

**Comment by Sebmaster** [comment] 2017-05-15 13:11
There is, but if you specify relative URLs, you need to provide a proper base URL on initialization, how would jsdom know how to resolve the relative URL otherwise?

**Comment by lukasoppermann** [comment] 2017-05-15 13:18
Okay, this is good. So if I am running a test via mocha and the file is in `/test/test.js` and the file I want to load in the jsdom created in /test/test.js` is located in `/dist/file.js`, how would I add a base URL? (Is it just by using the `url` property) and what would this url need to look like (I tried it, but had no luck).

I am not spinning up a node server or anything, the tests are just running via mocha. 

Thanks for your help.

**Comment by Sebmaster** [comment] 2017-05-15 13:26
You'll need to specify a file:/// url with the full path.

**Comment by domenic** [comment] 2017-05-15 15:51
Since "/" is not a valid URL, this should be throwing an exception telling you that it's not a valid URL... Is that not happening?

**Comment by lukasoppermann** [comment] 2017-05-15 15:57
No it was not. However adding the file:/// path I am still not able to require the file from within the jsdom using requirejs. 

Can I somehow provide some more helpful info? 

If I require '' (empty string) it works and onModulesLoaded is fired.

**Comment by domenic** [comment] 2017-05-16 02:45
I can't reproduce this: `new JSDOM(``, { url: "/" })` throws a TypeError for me.

Can you create a valid standalone test, that does not reference undefined variables like `requirejs`? I'll close this for now as it seems there is no issue with jsdom here.

**Closed** 2017-05-16 02:45 UTC

**Comment by lukasoppermann** [comment] 2017-05-16 04:26
Hey @domenic, require is defined, or else I would get an error for this.

What is not defined is `window.requiredSortable` which I test after the code above is run in the before of a mocha test.

Mocha throws: `AssertionError: expected undefined to be a function` which is the assertion below. Therefor I am pretty convinced it is a problem with the path. However, even after I looked thorugh the documentation, I can not figure out how to fix this. 😞 


```Javascript
describe('AMD (Asynchronous module definition)', function () {
    before(function () {
       window = (new JSDOM(``, { runScripts: 'dangerously', url: 'file:///Users/lukasoppermann/Code/html5sortable/' })).window
      const requirejs = require('fs').readFileSync('./node_modules/requirejs/require.js', { encoding: 'utf-8' })
      const scriptEl = window.document.createElement('script')
      scriptEl.textContent = requirejs
      window.document.head.appendChild(scriptEl)

      scriptEl.textContent = `
        window.require = require
        require(['./dist/html.sortable'], function (sortable) {
          window.requiredSortable = sortable
          window.onModulesLoaded()
        })`
        window.document.head.appendChild(scriptEl)
    })

    it('should define sortable', function () {
      window.onModulesLoaded = () => {
        console.log("ready to roll!");
      };

      assert.typeOf(window.requiredSortable, 'function')
    })
  })
```

**Comment by domenic** [comment] 2017-05-16 04:30
Here's the issue. I cannot run any of the code snippets you provide on my own to reproduce your problems. You need to give me a file I can run with `node test.js` without installing any extra dependencies. In your latest code snippet you are using various variables like describe, before, etc. which are not present in Node.js by default.

**Comment by lukasoppermann** [comment] 2017-05-16 04:33
Okay, sorry, I did not get this, I will provide a repo to test this.

**Comment by lukasoppermann** [comment] 2017-05-16 04:46
Okay, so the testcase is here:

```
git clone https://github.com/lukasoppermann/jsdom-test.git && cd jsdom-test && npm i
```

Once npm is done, simply run `npm test` and you can see my issue.

https://github.com/lukasoppermann/jsdom-test

Thank you for looking into it.

**Comment by lukasoppermann** [comment] 2017-05-22 07:11
Hey @domenic, did you by any chance have a chance to look at it yet? Cheers.

**Comment by NicoleRauch** [comment] 2017-07-28 11:52
@lukasoppermann I figured out what the problem with your test is: You run your assertion too early. If I move the assertions into the onModulesLoaded callback, the test is green on my machine:

```
    it('should define sortable', function () {
      window.onModulesLoaded = () => {
        console.log("ready to roll!");
        assert.typeOf(window.requirejs, 'function')
        assert.typeOf(window.requiredSortable, 'function')
      };
    })
```

**Comment by TimothyGu** [comment] 2017-07-28 13:39
@NicoleRauch `onModulesLoaded` is executed asynchronously, so the outside testing environment is unaware of any errors that may have occurred in `onModulesLoaded`.

**Comment by NicoleRauch** [comment] 2017-07-28 13:56
@TimothyGu Oops, good point! I adapted the test to make it wait for the async callback:

```
    it('should define sortable', function (done) {
      window.onModulesLoaded = () => {
        // ...
	done();
      };
    })
```

and now it runs into a timeout (in mocha). Increasing the mocha timeout duration shows that there is a timeout error in the require call:

```
Error: Uncaught [Error: Load timeout for modules: dist/html.sortable
http://requirejs.org/docs/errors.html#timeout]
```
So I guess this is rather a problem with the requirejs invocation than with jsdom?

**Comment by TimothyGu** [comment] 2017-07-28 14:56
@NicoleRauch Not sure, maybe it's jsdom's problem not being able to load `./dist/html.sortable.js` from `file:///Users/lukasoppermann/Code/html5sortable/`... jsdom internally [uses](https://github.com/tmpvar/jsdom/blob/9783072038ee7cf02fd980d7e2632de88f6ed45e/lib/jsdom/browser/resource-loader.js#L185) [request](https://www.npmjs.com/package/request) to fetch `<script>` resources, which may not handle `file:` URLs correctly.

**Comment by NicoleRauch** [comment] 2017-07-28 15:05
@TimothyGu Switching the `file:` URL to an `http:` URL (and firing up a small HTTP server that serves the required file) still gave me the same result. So I still suspect the require() invocation is the culprit but it's nothing more than speculation, so I will stop here :-)

**Comment by TimothyGu** [comment] 2017-07-28 15:38
@NicoleRauch Ah, thanks for testing!
