### ISSUE TITLE
custom 'data' attributes on tag elements are not reachable

### ISSUE THREAD

**Issue by MaxOrelus** [tmpvar/jsdom#1485] opened 2016-05-15 00:46 UTC
I'm using custom data attributes on my html pages. When I query for a DOM element and view all the attributes in the regular browser, I'm able to grab my HTML5 data attributes. When I try to do the same with jsdom, I have no problem grabbing the values for default tag attributes like `href`, `title`, `class`.

The issue seems to be when I try to grab attributes that are custom to my implementation, such as `data-source` or `data-something`. jsdom seems not to register these attributes as well, as does not have support for the `dataset` method on the DOM.

```js
    var document = window.document;
    
    console.log(document.querySelector('img').attributes);
    // this will return an object with the regular attributes intact
    // `src`, `title`, etc...
    // any `data-whatever` attribute shows up as an empty object
```

Also, `dataset` method on the DOM api is not supported

```js
document.querySelector('img').dataset;
// should return an object with all data attributes for that specific element
// instead it returns undefined
```

This seems like an issue or maybe even a feature request for a future version. Let me know if I should be doing something else to obtain the values for these data-attributes. I'm not using jquery or anything, simply using the base DOM api methods.

**Comment by domenic** [comment] 2016-05-15 00:49
Dataset is not yet supported. Can you show a complete repro snippet we can run to reproduce the other issue you describe?

**Comment by MaxOrelus** [comment] 2016-05-15 04:17
I actually got the other way to work. I think what was throwing me off was the console output node returns.

```js
var attr = document.querySelector('img');
    for (var i = 0; i < attr.length; i++) {
        console.log( attr[i].nodeName, attr[i].nodeValue);
    }
```

**Comment by domenic** [comment] 2016-05-15 04:27
Ah OK. I'll close this as a dupe of #961 then.

**Closed by domenic** 2016-05-15 04:27 UTC

**Comment by vsemozhetbyt** [comment] 2016-05-15 09:14
@MaxOrelus `Attr` properties inherited from `Node` are deprecated and will be removed from DOM. In your case it is better to use `attr[i].name ` and `attr[i].value`. See https://developer.mozilla.org/en-US/docs/Web/API/Attr .

**Comment by MaxOrelus** [comment] 2016-05-20 18:02
yeah, I forgot to add the `attributes` to the end of that statement.
