### ISSUE TITLE
querySelector within a fragment doesn't return SVG elements

### ISSUE THREAD

**Issue by lemnis** [tmpvar/jsdom#1986] opened 2017-09-22 17:43 UTC
### Basic info:

- **Node.js version: 6.11.2**
- **jsdom version: 11.2.0**

### Minimal reproduction case

```js
var {JSDOM} = require("jsdom")
var frag = JSDOM.fragment(`<svg></svg>`);
console.log(frag.querySelector("svg"));
console.log(frag.querySelector("*"));
```

`frag.querySelector("svg")` returns `null`, while the wildcard selector correctly returns the SVG element.

**Comment by TimothyGu** [comment] 2017-09-22 18:40
It seems to be a bug in nwmatcher (which we use for selector matching) for assuming all elements in an HTML document are actually HTML elements, and uppercases the matched string before matching. This is not the case for SVG-in-HTML.

https://github.com/dperini/nwmatcher/blob/effcec7b30065b270b2ce03c65ece8f5cb4b9028/src/nwmatcher-noqsa.js#L530-L533

So for the selector `svg` the following matching code is generated:

```js
if (e.nodeName == "SVG") {
  r[r.length] = c[k];
  if (f && false === f(c[k]))
    break main;
  else
    continue main;
}
```

while the HTML Standard actually [says](https://html.spec.whatwg.org/multipage/semantics-other.html#selectors)

> When comparing a CSS element type selector to the names of HTML elements in HTML documents, the CSS element type selector must first be converted to ASCII lowercase. The same selector when compared to other elements must be compared according to its original case. In both cases, the comparison is case-sensitive.

(The reason why the spec says "ASCII lowercase" is because the tag name is stored internally as lower case, but [exposed](https://dom.spec.whatwg.org/#dom-element-tagname) through `tagName` and therefore `nodeName` as upper case.)

So based on that, the generated code should probably look like

```js
if (e.namespaceURI === "http://www.w3.org/1999/xhtml" && e.nodeName === "SVG" ||
    e.nodeName === "svg") {
  r[r.length]=c[k];
  if (f && false === f(c[k]))
    break main;
  else
    continue main;
}
```

for HTML documents.

@dperini can you weigh in?

**Comment by lemnis** [comment] 2017-09-22 19:10
Just for clarification, **all** svg elements return `null`, e.g. beneath code will only log `null`

```html
var {JSDOM} = require("jsdom")
var frag = JSDOM.fragment(`<svg><path /><rect /></svg>`);
console.log(frag.querySelector("svg"));
console.log(frag.querySelector("path"));
console.log(frag.querySelector("rect"));
```

P.s. it's the "http://www.w3.org/2000/svg" namespace 😉

**Comment by TimothyGu** [comment] 2017-09-22 19:29
@lemnis 

> P.s. it's the "http://www.w3.org/2000/svg" namespace

Well we want to use "SVG" when it's the HTML namespace, for cases like `document.createElementNS("http://www.w3.org/1999/xhtml", "svg").nodeName === "SVG"`.

**Comment by dperini** [comment] 2017-09-24 10:51
Looking in to this issue thank you for the report.
From a quick reading of your issue, what I can say now is that "nwmatcher" has no specific "namespace" support and it looks like you are not using it in an HTML document but in an XHTML document. Have you tried switching to an HTML doctype ?

**Comment by TimothyGu** [comment] 2017-09-27 03:09
@dperini The case is quite the opposite actually: using XML elements in an HTML document. I did realize that nwmatcher has no namespace support, but this issue isn't really about namespace support, but instead about conforming to DOM Standard's definition of `nodeName`.

**Comment by dperini** [comment] 2017-09-27 14:29
This is what I get from node/jsdom using your suggested test:

    var {JSDOM} = require("jsdom")
    var frag = JSDOM.fragment(`<svg></svg>`);
    console.log(frag.querySelector("svg"));
    console.log(frag.querySelector("*"));

    null
    HTMLUnknownElement {}

this is what I get in any browser using the `createElementNS` as you said:

    var frag = document.createDocumentFragment();
    var element = document.createElementNS("http://www.w3.org/1999/xhtml", "svg");
    frag.appendChild(element);
    console.log(frag.querySelector("svg"));
    console.log(frag.querySelector("*"));
    console.log(NW.Dom.first("svg", frag));
    console.log(NW.Dom.first("*", frag));

    <svg>
    <svg>
    <svg>
    <svg>

what am I missing ? I see `nwmatcher` prints correct results.

Seems the browsers agree with the expected results while jsdom does not recognize SVG elements but it treats them as "HTMLUnknownElement {}".

Can you run/test the the above javascript in your browser and tell what you see ?

**Comment by TimothyGu** [comment] 2017-09-27 17:15
@dperini You should test the current master branch:

```
> var {JSDOM} = require(".")
> var frag = JSDOM.fragment(`<svg></svg>`);
> console.log(frag.querySelector("svg"));
null
> console.log(frag.querySelector("*"));
Element {}
```

Just like how in browsers `<svg>` is printed for both, `Element {}` should be printed for both queries.

----

> while jsdom does not recognize SVG elements but it treats them as "HTMLUnknownElement {}".

nwmatcher supported matching HTMLUnknownElement for other elements, just not svg because it was created in a different namespace.

```js
> var frag = JSDOM.fragment(`<asdfadsf></asdfadsf>`);
> console.log(frag.querySelector("asdfadsf"));
HTMLUnknownElement {}
```

----

The crux of the problem is that nwmatcher assumes all elements in an HTML document are HTML elements. That's not true for elements like `<svg>`.

**Comment by dperini** [comment] 2017-09-27 23:28
Well, let's get to the point ...
how do I create a an element having a lowercase `nodeName` in an HTML Document ?
If I can do that  I can probably find a fix, elsewhere it will be hard or almost impossible.
You have already seen that the suggested test:

    var element = document.createElementNS("http://www.w3.org/1999/xhtml", "svg");

creates an element having the `nodeName` property as uppercase even if using NS creation.

By the way ... `nwmatcher` does as few assumptions as possible, it does live feature testing of the outcome of element creation for each document that is submitted for selection, that's exactly to avoid these kind of problems in different environments (see the isHTML() & switchContext() methods).

I am willing to help with a solution but need to be pragmatic, I need to find the way to create elements exposing lowercase `nodeName` property, the only place I find this is in the `localName` but even with that we will not be able to cover all the cases since it is always lowercase.

**Comment by TimothyGu** [comment] 2017-09-27 23:49
> how do I create a an element having a lowercase `nodeName` in an HTML Document ?

There are multiple ways you can do that.

### Through HTML

```html
<svg></svg>
```

### Through the DOM

```js
var literallyAnythingOtherThanHTMLNamespace = "http://www.w3.org/2000/svg";
var element = document.createElementNS(literallyAnythingOtherThanHTMLNamespace, "svg");
```

### Through the DOM but with innerHTML

```js
var tmpl = document.createElement('template');
tmpl.innerHTML = '<svg></svg>';
var element = tmpl.content.children[0];
```

----

> You have already seen that the suggested test:
>
> ```js
> var element = document.createElementNS("http://www.w3.org/1999/xhtml", "svg");
> ```
>
> creates an element having the nodeName property as uppercase even if using NS creation.

I was using that as a counterexample. By default SVG elements do not use the HTML namespace, even when they are in HTML documents.

**Comment by dperini** [comment] 2017-09-29 19:56
So, from the above examples, I assume that it is possible to have an `svg` element with lower case `nodeName` only by declaring it as part of the "http://www.w3.org/2000/svg" namespace.
Declaring it as part of a different namespace like "http://www.w3.org/1999/xhtml" doesn't work.

Are these assumptions correct ?

I am trying to see if there are alternatives that allows maintaining the current performances.
The only options I see up to now is to introduce a new Config.SVG_CHECK for this exact excption, otherwise the proposed solution to check for both lower & upper cases will slow down all other selections by 2x which is not acceptable.

I will setup some example test cases this weekend, I recall in the past I have been told that `nwmatcher` had no problems handling SVG elements in either HTML, XHTML or SVG documents.

Thank you for your patience and help.

**Comment by TimothyGu** [comment] 2017-09-29 20:16
> ... only by declaring it as part of the "http://www.w3.org/2000/svg" namespace.  
> Declaring it as part of a different namespace like "http://www.w3.org/1999/xhtml" doesn't work.

Actually, declaring it as part of *any* namespace *but* "http://www.w3.org/1999/xhtml" would work. Nor is this quirk exclusive to SVG.

```js
console.log(document.createElementNS("asdfdsafasd", "anyelement").nodeName);
// anyelement
```

The relevant parts of the DOM Standard are:

- https://dom.spec.whatwg.org/#dom-node-nodename, which redirects to
- https://dom.spec.whatwg.org/#dom-element-tagname

> The only options I see up to now is to introduce a new Config.SVG_CHECK for this exact excption, otherwise the proposed solution to check for both lower & upper cases will slow down all other selections by 2x which is not acceptable.

Again, this applies not only to SVG, but in fact to all elements in an HTML document that are not in the HTML namespace.

Unfortunately, that is what the specifications demand. Unless you want to claim noncompliance with the specs (if only with regards to non-HTML-namespaced elements in HTML documents), this is necessary for HTML documents.

> I will setup some example test cases this weekend, I recall in the past I have been told that nwmatcher had no problems handling SVG elements in either HTML, XHTML or SVG documents.

XHTML and SVG documents are fine, because they are both considered XML documents by the specs, which nwmatcher implements correctly.

This issue quite obviously shows there is an issue with how SVG elements are treated in HTML documents.

**Comment by TimothyGu** [comment] 2017-09-29 20:30
Correction:

I was mistaken in my last comment about the performance impact. Using `localName` instead of `nodeName` for matching would solve both this issue in a performant way and another compliance issue, detailed below:

```js
var element = document.createElementNS('namespace', 'ns:abc');
document.body.appendChild(element);
console.log(document.querySelector('abc'));
// Currently this logs null.
// In browsers this logs <ns:abc>.
```

I will create a PR for nwmatcher for you to review shortly, with appropriate tests.

**Comment by dperini** [comment] 2017-10-11 20:03
A fix has been included in version 1.4.3, which will be pushed to `npm` a.s.a.p.

Since it is an exception to the rules it will only be enabled by configuring the special flag `SVG_LCASE` using the following syntax:

    NW.Dom.configure({ SVG_LCASE: true });

it is disabled (false) by default.
Thank you for the report.

**Comment by caub** [comment] 2017-10-12 18:33
yes nwmatcher 1.4.3 fixes this issue

```js
console.log(JSDOM.fragment('<svg></svg>').querySelector('svg')) // SVGElement {} (on a different branch)
```

**Comment by dperini** [comment] 2017-10-13 01:02
Thank you for the feedback, appreciated.
Have fun !

**Comment by dperini** [comment] 2017-11-06 16:58
I believe that this issue can be closed.
NWMatcher 1.4.3 has a new configuration flag for this.
It is named SVG_LCASE to support SVG elements in HTML documents.

Use the following method and syntax to enable this new feature:

     NW.Dom.configure({ SVG_LCASE: true });

**Comment by domenic** [comment] 2017-11-06 17:07
Yeah, we need to enable it and test it before we can close the issue, but probably the work on nwmatcher's side is done.

**Comment by dperini** [comment] 2017-11-06 18:01
Got it, thank you !

**Closed** 2017-11-19 21:33 UTC
