### ISSUE TITLE
XHTML serialization breaks self-closing tags

### ISSUE THREAD

**Issue by drochgenius** [tmpvar/jsdom#1839] opened 2017-05-04 12:53 UTC
XHTML requires some tags to have a self-closing ending `/>`.
This is the case for: `meta`, `link`, `img`, `br` for example.
However, when  serializing the DOM tree from JSDOM serialize(), the tags are missing the `/>` at the end, which breaks XHTML compliance.

I can surely fix this with some regex magic, but I'd like to know if there's a way to force JSON to serialize those properly.

There is documentation for this, but it doesn't seem to work.

Reproduction info below.

Thanks for your support

Dominique

### Basic info:

- **Node.js version: 6.10.2** 
- **jsdom version: 10.1.0** 

### Minimal reproduction case

XHTML sample:
```html
<?xml version='1.0' encoding='UTF-8' ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title>Test xhtml document</title>
  <meta charset="utf-8" />
  <link type="text/css" title="default" rel="stylesheet" href="assets/css/epub_main.css" />
</head>
<body>
  <section epub:type="toc" xmlns:epub="http://www.idpf.org/2007/ops">
    <header>
      <h1>Title</h1>
      <img src="some-image.png" />
    </header>
  </section>
</body>
</html>
```

TEST 1:
```js
const { JSDOM } = require("jsdom");

const xml = fs.readFileSync('test/test.xhtml', 'utf-8');
const dom = new JSDOM(xml);
fs.writeFileSync('test/output1.xhtml', dom.serialize(), 'utf-8');

```

TEST 2:
```js
const { JSDOM } = require("jsdom");

const xml = fs.readFileSync('test/test.xhtml', 'utf-8');
const dom = new JSDOM(xml, { contentType: 'application/xhtml+xml' });
fs.writeFileSync('test/output2.xhtml', dom.serialize(), 'utf-8');
```

TEST 3: using the fromFile() utility
```js
const { JSDOM } = require("jsdom");

JSDOM.fromFile('test/test.xhtml').then(dom => {
    fs.writeFileSync('test/output3.xhtml', dom.serialize(), 'utf-8');
});
```

Now if you look at the serialized output files, you'll see that some tags are not closed:

```html
<meta charset="utf-8">
<link type="text/css" title="default" rel="stylesheet" href="assets/css/epub_main.css">
(...)
<img src="some-image.png">
```

**Comment by Sebmaster** [comment] 2017-05-04 12:56
Parsing is XHTML compliant, serialization is always HTML however, for lack of a easy standards compliant XML Serializer.

Dupe of #798.

**Closed by Sebmaster** 2017-05-04 12:56 UTC

**Comment by drochgenius** [comment] 2017-05-05 13:16
Just to let the community know that this worked for me:
https://github.com/cburgmer/xmlserializer

Basically, after serializing from `jsdom`, I get an HTML string.

Then, I pass this HTML string through the function `html2xhtml()` below, and I get the expected XHTML-compliant output.

```javascript
/**
 * This module provides methods to convert HTML to XHTML
 */
const { parse } = require('parse5');
const { serializeToString } = require('xmlserializer');

const xmlHeader = '<?xml version=\'1.0\' encoding=\'UTF-8\' ?>\n';

/**
 * Convert a standard HTML5 string to XHTML-compliant string
 * 
 * @param {string} htmlString : html string to convert to xhtml
 */
function html2xhtml(htmlString) {
    const dom = parse(htmlString);
    return xmlHeader + serializeToString(dom);
}

module.exports = { html2xhtml };
```

Hopefully this can help others facing a similar issue.

Regards

Dominique

**Comment by noelelias** [comment] 2022-07-13 11:25
Solution for preparing the HTML before sending it off to jsdom:
`
const contentPrecompile = (content) => {
  return content.replaceAll(/<(.*?) .*?\/>/gm, (match, tagName) => {
    return `${match.slice(0, -2)}></${tagName}>`;
  });
  `
