### ISSUE TITLE
textContent vs. innerText

### ISSUE THREAD

**Issue by BobFrGit** [tmpvar/jsdom#1596] opened 2016-09-08 00:09 UTC
innerText returns null but textContent works.

In the browser:

```
<!DOCTYPE html>
<html><head><title>JS Bin</title>
</head><body></body></html>

var tt = document.getElementsByTagName("title")[0];
console.log("Content: " + tt.textContent);
console.log("Inner:  "  + tt.innerText);

"Content: JS Bin"
"Inner:  JS Bin"

**** In Node with JSDOM ***
{
   let jd = jsd.jsdom("<!DOCTYPE html><html><head><title>JS Bin</title></head><body></body> </html>");
    var tt =jd.getElementsByTagName("title")[0];
    console.log("Content: " + tt.textContent);
    console.log("Inner:  " + tt.innerText);
}

Content: JS Bin
Inner:  undefined
```

**Comment by domenic** [comment] 2016-09-08 00:11
Yeah. Dupe of #1245. Thanks for the nice test case!

**Closed by domenic** 2016-09-08 00:11 UTC
