### ISSUE TITLE
Radio button click does not cause change event

### ISSUE THREAD

**Issue by liqwid** [tmpvar/jsdom#2037] opened 2017-10-30 16:19 UTC
### Basic info:

- **Node.js version:** 8
- **jsdom version:** 11.3.0

Inputs without radio do not trigger a change event, although in browser they do.

### Minimal reproduction case

Below is the source code of jsdom which describes the extra input events:
```js
  // HTMLInputElement-impl.js
  ...
  _activationBehavior() {
    if (isDisabled(this)) {
      return;
    }

    if (this.type === "checkbox") {
      const inputEvent = Event.createImpl(["input", { bubbles: true, cancelable: true }], {});
      this.dispatchEvent(inputEvent);

      const changeEvent = Event.createImpl(["change", { bubbles: true, cancelable: true }], {});
      this.dispatchEvent(changeEvent);
  ...
```

This bug could be easily fixed by adding radio type along with checkbox:
```js
if (this.type === "checkbox" || this.type === "radio") {
```

Still I'm not completely sure why is "input" event triggered and if it should be triggered on radio button. I did not manage to trigger it in browser.

### How does similar code behave in browsers?

Radio button click as well as checkbox causes change event followed by a click event.
http://plnkr.co/edit/PoFSKwBWGWKt0IemPLHM?p=preview

**Comment by domenic** [comment] 2017-10-30 16:29
This unfortunately doesn't follow the issue template. It quotes jsdom source code, but does not provide code I can run to reproduce the claimed issue. So, let me close this. Please add a comment when you have edited your post to match the issue template.

**Comment by liqwid** [comment] 2017-10-30 17:22
Here is the example:

```js
const jsdom = require("jsdom");
const { JSDOM } = jsdom;

const dom = new JSDOM(`
  <!doctype html>
  <html>
    <head>
    </head>
    <body>
      <form>
      <label class="btn btn-primary" for="radioBtn">Left</label>
      <input type="radio" id="radioBtn" name="group"/>
      <label class="btn btn-primary" for="checkbox">Check</label>
      <input type="checkbox" id="checkbox"/>
      </form>
      <script src="example.js"></script>
    </body>
  </html>
`);

const { document } = dom.window;

const radioButton = document.getElementById('radioBtn');
radioButton.addEventListener('click', () => {console.log('radio clicked')});
radioButton.addEventListener('change', () => {console.log('radio changed')});
radioButton.addEventListener('input', () => {console.log('radio input')});

const checkBox = document.getElementById('checkbox');
checkBox.addEventListener('click', () => {console.log('checkbox clicked')});
checkBox.addEventListener('change', () => {console.log('checkbox changed')});
checkBox.addEventListener('input', () => {console.log('checkbox input')});

const form = document.querySelector('form');
form.addEventListener('input', () => {console.log('input')});

document.querySelector('label[for="radioBtn"]').click();
document.querySelector('label[for="checkbox"]').click();
```

**Comment by domenic** [comment] 2017-10-30 17:28
Thanks! How does that behave in Node? And how does it behave in browsers?

**Comment by liqwid** [comment] 2017-10-30 17:30
In node:
click label => no radio button change event
In browsers:
click label => radio button change event dispatched, see example in the opening post

**Comment by liqwid** [comment] 2017-10-31 11:09
@domenic I want to make a pull request on this one however I've encountered a problem with launching tuwpt tests: they all (with or without fgrep) fail with the following error:
`Error: getaddrinfo ENOTFOUND web-platform.test web-platform.test:10000`

Did you encounter such a problem?

**Comment by domenic** [comment] 2017-10-31 11:11
Check out contributing.md which documents what you have to do to set up your environment.

**Comment by liqwid** [comment] 2017-10-31 18:24
There's more behavior in this case:

Already checked radio input should only emit click, I'll update pull request shortly

**Comment by liqwid** [comment] 2017-10-31 21:11
Published an update to a pull request

**Comment by domenic** [comment] 2017-11-19 20:51
Great stuff; sorry for the delay. It looks like our setup for the pre-click/activation/etc. does not quite match the spec; the spec is pretty complicated for radio buttons. But, this is closer, at least, so let me pull it in.

**Comment by domenic** [comment] 2017-11-19 21:00
Well, it's not closer to the spec, but it is closer to browsers... You found a spec bug! https://github.com/whatwg/html/issues/3239

**Closed** 2017-11-19 21:17 UTC
Labels: bug
