### ISSUE TITLE
How to create listener on dom content change?

### ISSUE THREAD

**Issue by zhaoyi0113** [tmpvar/jsdom#1931] opened 2017-08-07 06:49 UTC
I use below code to create a dom and want to listen on its content change.

> const termDom = new JSDOM(`<!DOCTYPE html><div id="terminal"/>`);
> const dom = termDom.window.document.querySelector("#terminal");

I want to add a listener on this dom to listen on its content changes. Something like:

> dom.onChange( function(event) {
>      ...
> })

How can I implement it in`jsdom`?

**Comment by vsemozhetbyt** [comment] 2017-08-07 08:34
I was thinking about [MutationObserver](https://developer.mozilla.org/en/docs/Web/API/MutationObserver), but it seems that `dom.window.MutationObserver` is `undefined` in `jsdom`.

**Comment by TimothyGu** [comment] 2017-08-07 09:09
Duplicate of #639.

**Closed** 2017-08-07 11:28 UTC
