### ISSUE TITLE
Question: CustomEvents 

### ISSUE THREAD

**Issue by mendrik** [tmpvar/jsdom#812] opened 2014-06-27 12:39 UTC
Does jsdom suppot CustomEvents with ev.details?
My code has the well known polyfill:
```
(function () {
    function CustomEvent ( event, params ) {
        params = params || { bubbles: false, cancelable: false, detail: undefined };
        var evt = document.createEvent( 'CustomEvent' );
        evt.initCustomEvent( event, params.bubbles, params.cancelable, params.detail );
        return evt;
    }
    if (!!window.CustomEvent) CustomEvent.prototype = window.CustomEvent.prototype;
    window.CustomEvent = CustomEvent;
})();
```
but it fails on evt.initCustomEvent. Now my questions is whether this will be fixed at some point or is there some work-around for it? I really rely on customevents in my site.

**Comment by domenic** [comment] 2015-06-26 12:49
Dupe of #611.

**Closed by domenic** 2015-06-26 12:49 UTC
Labels: dom living standard
