### ISSUE TITLE
Keyboard events

### ISSUE THREAD

**Issue by JacksonGariety** [tmpvar/jsdom#730] opened 2014-01-25 03:19 UTC
I see the commented-out DOM source includes keyboard events.

Assuming they aren't already implemented, how would I go about adding them to JSDOM? Is there any reason they haven't been implemented already? Would this be trivial for me to add myself?

**Comment by dbrans** [comment] 2015-10-29 22:54
+1

**Comment by domenic** [comment] 2015-11-26 06:35
Fixed by https://github.com/tmpvar/jsdom/commit/5459bec38660658e4e18642265f61c3d79e984dd

**Closed by domenic** 2015-11-26 06:35 UTC

**Comment by edrpls** [comment] 2015-12-08 21:00
Hi, unfortunately I'm stuck on an older Node version, is there any other way to trigger keyboard events?

**Comment by Sebmaster** [comment] 2015-12-08 21:06
No, `KeyboardEvent`s were never implemented before this change.

**Comment by edrpls** [comment] 2015-12-08 21:07
Okay, thanks for your response.

**Comment by Joris-van-der-Wel** [comment] 2015-12-08 22:29
Have you tried using [nvm](https://github.com/creationix/nvm) to install the latest node? (you do not need root)

**Comment by edrpls** [comment] 2015-12-08 22:31
Thanks for the suggestion, but the problem is that it will run on a corp machine with a specific version that can't be modified from the outside.
