### ISSUE TITLE
 set up js dom for getBoundingClientRect()  

### ISSUE THREAD

**Issue by potapovDim** [tmpvar/jsdom#1590] opened 2016-08-25 14:01 UTC
![screen shot 2016-08-25 at 4 57 33 pm](https://cloud.githubusercontent.com/assets/19333856/17971933/84dc4b34-6ae5-11e6-9007-5d51289fb77b.png)

maybe somebody setups jsdom that it work with  getBoundingClientRect()  , i work with simulantjs and my console log back this->
![screen shot 2016-08-25 at 5 03 42 pm](https://cloud.githubusercontent.com/assets/19333856/17972014/ece3fa42-6ae5-11e6-9f7a-aa534277a8f5.png)

```
    const wrapper = mount(
      <Provider store={store}>
        <FullDecoratedBlock
          uid={'test'}
          setFocusedElement={setFocusedElement}/>
      </Provider>, {attachTo: document.getElementById('app')})
    expect(wrapper.find('.add-wrap').length).to.eql(0)
    simulant.fire(document.body.querySelector('.wrapper-resize-button'), 'mousedown')
    simulant.fire(document.body, 'mousemove', {target: {clientX: 51, clientY: 101}})
```

maybe someone has ideas??

**Comment by domenic** [comment] 2016-08-25 14:30
I can't understand this issue very well. It seems like maybe it is a dupe of #1581, https://github.com/tmpvar/jsdom/issues/653, https://github.com/tmpvar/jsdom/issues/1322.

**Comment by potapovDim** [comment] 2016-08-25 15:10
@domenic  i have component , when i move mouse to bottom of component , i wait that my component show buttop , and it bount to `const rect = node.getBoundingClientRect()`  frow this rect get coordinates of mouse , and in component write `const showPlusButton = event.insideX && Math.abs(event.pos.y - event.componentRect.bottom) <= MOUSE_DISTANCE` when i move mouse i always get second screenshot

**Comment by Sebmaster** [comment] 2016-08-29 19:28
jsdom doesn't do any rendering, so `getBoundingClientRect()` always returns 0,0,0,0. That won't change (even foreseeable long-term). You can try to mock the function to emulate the results you'd expect. Also see #653.

**Closed by Sebmaster** 2016-08-29 19:28 UTC

**Comment by clearyandzap** [comment] 2020-01-25 00:09
You can assume the <Element/>.getBoundingClientRect() API works and do the following: 

```
const p = document.createElement('p')

    p.getBoundingClientRect = jest.fn(() => ({
      x: 851.671875,
      y: 200.046875,
      width: 8.34375,
      height: 17,
      top: 967.046875,
      right: 860.015625,
      bottom: 984.046875,
      left: 851.671875,
    }))
```

**Comment by leslie555** [comment] 2023-01-12 02:20
Update, I think using the way below is more suitable.
```
window.HTMLElement.prototype.getBoundingClientRect = () => ({
    bottom: 44,
    height: 24,
    left: 10,
    right: 35.67,
    top: 20,
    width: 25.67,
  } as DOMRect);
