### ISSUE TITLE
'onScroll' event not supported

### ISSUE THREAD

**Issue by hammer65** [tmpvar/jsdom#1873] opened 2017-05-31 17:01 UTC
### Basic info:

Node: 7.1.0
JSDOM: 10.1.0

### Minimal reproduction case

I have a React component which uses the onScroll event. it works fine in the browser but throws this error in testing. I understand that JSDOM can't support all such things but I don't want the error to appear. Is there a way for me to supress this error or stub it in some way?

```
․Warning: This browser doesn't support the `onScroll` event
```

### How does similar code behave in browsers?

No in browser errors

**Comment by Sebmaster** [comment] 2017-05-31 17:05
Since jsdom doesn't do rendering it can't really "scroll" (since it doesn't know how high any given element is). You'll have to figure out why it throws that error, you can easily stub whatever checks the component does immediately after constructing your window.

**Comment by domenic** [comment] 2017-05-31 17:27
We can't debug this without an actual reproduction case, so I'll have to close this.

**Comment by hammer65** [comment] 2017-05-31 17:27
it's a scrolling table so the element which has an onScroll attached to it is a <tbody> element. Is this error not coming from JSDOM but from REACT?

**Closed by domenic** 2017-05-31 17:27 UTC
Labels: question

**Comment by Sebmaster** [comment] 2017-05-31 17:35
Yes, that's a react error.
