### ISSUE TITLE
`querySelector` cannot resolve selectors with escaped IDs

### ISSUE THREAD

**Issue by bellbind** [tmpvar/jsdom#1550] opened 2016-07-04 07:00 UTC
For example, as a CSS selector, ID as `"0foo.000"` requires escape the first `"0"` and `"."` at least.
Current browsers also have `CSS.escape(str)` builtin for escaping any IDs.

But the current jsdom (9.4.0) cannot resolve the ID above. the code as:

``` js
"use strict";

const jsdom = require("jsdom");
const document = jsdom.jsdom();

//(same codes on web console and nodejs)
const elems = document.createElement("div");
const a = document.createElement("span");
a.id = "0foo.000";
elems.appendChild(a);

//fail with jsdom but pass on browsers
console.assert(elems.querySelector("#\\30 foo\\.000") === a);
```

**Comment by domenic** [comment] 2016-07-04 16:15
@dperini Any thoughts on supporting these in nwmatcher?

**Comment by dperini** [comment] 2016-07-05 00:30
@domenic The WIP code was already published in the "test/preview" directory of the "nwmatcher" repository as an answer to request/issue https://github.com/dperini/nwmatcher/issues/99 by user @almost, though it was a bad coding night and I didn't want to risk an "EPIC FAILURE" on npm.

However, since this did pop up frequently in the last weeks (see probable related issue https://github.com/dperini/nwmatcher/issues/102) maybe I should re-work the patched WIP code improve it and publish. Maybe you can help by testing/reviewing the changes since it is a bit complicated due to the way I implemented it (an option disabled by default that can be enabled using NW.Dom.configure).

I did it this way to avoid inducing users to bad habits and to treat that as exceptions, however I am not clear if this will make it difficult to get to NW.Dom.configure from "jsdom". I just don't remember.

Suggestions idea and tests are obviously welcome.

**Comment by dperini** [comment] 2016-07-05 00:58
@bellbind could you help test https://github.com/dperini/nwmatcher/blob/master/test/preview/nwmatcher.js and see if that WIP solves the issue ?
In that code you can enable the requested feature by using NW.Dom.configure({ ESCAPED: true }).

**Comment by bellbind** [comment] 2016-07-05 09:17
`nwmatcher.byId("\\30 0", elems)` returned `HTMLSpanElement {}`, but `nwmatcher.first("#\\30 0", elems)` returned `null` and `nwmatcher.select("#\\30 0", elems)` returned `[]`.

----

I think `String.fromCodePoint(uint32)` is prefer than `String.fromCharCode(uint16)` for non-BMP unicode chars(e.g. Emoji) in `unescapeIdentifier` function.

**Comment by bellbind** [comment] 2016-07-06 08:05
I wrote 3 line-comments for passing the code above to the commit dperini/nwmatcher@e9fc8f11a739f1f7f54bb7807e9dcff5438a8702 .

**Comment by dperini** [comment] 2016-07-06 10:56
That fixed it, thank you. I already pushed the commit to the WIP in test/preview.
Now I need to run all my local tests to check for errors and add more improvements.
Also adding the one you suggested about String.fromCodePoint preferred to String.fromCharCode.
However I have to think about a compatible solution for that change that since String.fromCodePoint is much slower than String.fromCharCode and absent in older IE and other older browsers.
Maybe something like the following will maintain performance & compatibility in most used cases:

          return codePoint > 0xffff && codePoint < 0x110000 && String.fromCodePoint ?
              String.fromCodePoint(codePoint) : String.fromCharCode(codePoint);

This avoids the code payload of a polyfill and still do the job.
Suggestions are very much welcome.

**Comment by bellbind** [comment] 2016-07-06 16:31
I comment to dperini/nwmatcher@46c571be53c4c02f84aafdfe172e4b63bbe301ea with processing a code point to surrogate pair char codes for the function.

Non-BMP characters are usually used today with Emojis.
Not only Emojis, these characters are used in normal words(like ABC of alphabet) for Chinese and Japanese.

- https://en.wikipedia.org/wiki/UTF-16
- https://en.wikipedia.org/wiki/Plane_(Unicode)

**Comment by dperini** [comment] 2016-07-07 14:49
Pushed the new suggested changes https://github.com/dperini/nwmatcher/commit/4f49c30
this is still only for testing the WIP in test/preview/nwmatcher.js .

**Comment by bellbind** [comment] 2016-07-14 07:45
I cant tackle several days from this weekend. 
So I made complete test cases for DOM `querySelector` from CSS syntax specification and test codes in chromium. it is already passed on firefox/chrome.

```js
"use strict";

// preparation for jsdom on nodejs (not entered on browsers)
if (typeof document === "undefined") {
  const jsdom = require("jsdom");
  var document = jsdom.jsdom();
}

function testMatched(id, selector) {
  const elems = document.createElement("div");
  const a = document.createElement("span");
  a.id = id;
  elems.appendChild(a);
  console.assert(
    elems.querySelector(selector) === a,
    `${JSON.stringify(id)} should match with ${JSON.stringify(selector)}`);
}
function testNeverMatched(id, selector) {
  const elems = document.createElement("div");
  const a = document.createElement("span");
  a.id = id;
  elems.appendChild(a);
  console.assert(
    elems.querySelector(selector) === null,
    `${JSON.stringify(id)} should never match with ${
        JSON.stringify(selector)}`);
}

// 4.3.7 from https://www.w3.org/TR/css-syntax-3/#consume-an-escaped-code-point
testMatched("nonescaped", "#nonescaped");

// - escape hex digit
testMatched("0nextIsWhiteSpace", "#\\30 nextIsWhiteSpace");
testMatched("0nextIsNotHexLetters", "#\\30nextIsNotHexLetters");
testMatched("0connectHexMoreThan6Hex", "#\\000030connectHexMoreThan6Hex");
testMatched("0spaceMoreThan6Hex", "#\\000030 spaceMoreThan6Hex");

// - hex digit special replacement
// 1. zero points
testMatched("zero\u{fffd}", "#zero\\0");
testNeverMatched("zero\u{0}", "#zero\\0");
testMatched("zero\u{fffd}", "#zero\\000000");
testNeverMatched("zero\u{0}", "#zero\\000000");
// 2. surrogate points
testMatched("\u{fffd}surrogateFirst", "#\\d83d surrogateFirst");
testNeverMatched("\ud83dsurrogateFirst", "#\\d83d surrogateFirst");
testMatched("surrogateSecond\u{fffd}", "#surrogateSecond\\dd11");
testNeverMatched("surrogateSecond\udd11", "#surrogateSecond\\dd11");
testMatched("surrogatePair\u{fffd}\u{fffd}", "#surrogatePair\\d83d\\dd11");
testNeverMatched(
  "surrogatePair\u{1f511}", "#surrogatePair\\d83d\\dd11");
// 3. out of range points
testMatched("outOfRange\u{fffd}", "#outOfRange\\110000");
testMatched("outOfRange\u{fffd}", "#outOfRange\\110030");
testNeverMatched("outOfRange\u{30}", "#outOfRange\\110030");
testMatched("outOfRange\u{fffd}", "#outOfRange\\555555");
testMatched("outOfRange\u{fffd}", "#outOfRange\\ffffff");

// - escape EOF
testMatched("eof\u{fffd}", "#eof\\");
testNeverMatched("eof\\", "#eof\\");

// - escape anythong else
testMatched(".comma", "#\\.comma");
testMatched("-minus", "#\\-minus");
testMatched("g", "#\\g");

// non edge cases
testMatched("aBMPRegular", "#\\61 BMPRegular");
testMatched("\u{1f511}nonBMP", "#\\1f511 nonBMP");
testMatched("00continueEscapes", "#\\30\\30 continueEscapes");
testMatched("00continueEscapes", "#\\30 \\30 continueEscapes");
testMatched("continueEscapes00", "#continueEscapes\\30 \\30 ");
testMatched("continueEscapes00", "#continueEscapes\\30 \\30");
testMatched("continueEscapes00", "#continueEscapes\\30\\30 ");
testMatched("continueEscapes00", "#continueEscapes\\30\\30");


// ident tests case from CSS tests of chromium source: https://goo.gl/3Cxdov
testMatched("hello", "#hel\\6Co");
testMatched("&B", "#\\26 B");
testMatched("hello", "#hel\\6C o");
testMatched("spaces", "#spac\\65\r\ns");
testMatched("spaces", "#sp\\61\tc\\65\fs");
testMatched("test\u{D799}", "#test\\D799");
testMatched("\u{E000}", "#\\E000");
testMatched("test", "#te\\s\\t");
testMatched("spaces in\tident", "#spaces\\ in\\\tident");
testMatched(".,:!", "#\\.\\,\\:\\!");
testMatched("null\u{fffd}", "#null\\0");
testMatched("null\u{fffd}", "#null\\0000");
testMatched("large\u{fffd}", "#large\\110000");
testMatched("large\u{fffd}", "#large\\23456a");
testMatched("surrogate\u{fffd}", "#surrogate\\D800");
testMatched("surrogate\u{fffd}", "#surrogate\\0DBAC");
testMatched("\u{fffd}surrogate", "#\\00DFFFsurrogate");
testMatched("\u{10ffff}", "#\\10fFfF");
testMatched("\u{10ffff}0", "#\\10fFfF0");
testMatched("\u{100000}00", "#\\10000000");
testMatched("eof\u{fffd}", "#eof\\");

testMatched("simple-ident", "#simple-ident");
testMatched("testing123", "#testing123");
testMatched("_underscore", "#_underscore");
testMatched("-text", "#-text");
testMatched("-m", "#-\\6d");
testMatched("--abc", "#--abc");
testMatched("--", "#--");
testMatched("--11", "#--11");
testMatched("---", "#---");
testMatched("\u{2003}", "#\u{2003}");
testMatched("\u{A0}", "#\u{A0}");
testMatched("\u{1234}", "#\u{1234}");
testMatched("\u{12345}", "#\u{12345}");
testMatched("\u{fffd}", "#\u{0}");
testMatched("ab\u{fffd}c", "#ab\u{0}c");
```
I think this issue would be fixed with this code passed.

This code is uploaded at: https://gist.github.com/bellbind/1dbbade5e36f55f4f1f3118ab21e7e71

----

Reference

- CSS syntax module: https://www.w3.org/TR/css-syntax-3/#consume-an-escaped-code-point
- chromium tests for CSS tokenize: https://goo.gl/3Cxdov

**Comment by steambap** [comment] 2016-08-01 23:06
I had the same issue. Is it possible to include this: [https://github.com/mathiasbynens/CSS.escape](https://github.com/mathiasbynens/CSS.escape) in jsdom to handle css escape?

**Comment by dperini** [comment] 2016-10-12 22:34
Support for escaped CSS identifiers has finally landed in nwmatcher since this commit:

https://github.com/dperini/nwmatcher/commit/723bda0

fully fixed to pass the provided test in this last commit:

https://github.com/dperini/nwmatcher/commit/9edf1e6

please test, confirm and close the issue if positive.

**Comment by domenic** [comment] 2016-10-15 14:05
Confirmed that this is fixed by the nwmatcher beta! I posted https://github.com/tmpvar/jsdom/pull/1627 to add the tests that @bellbind wrote (awesome job!!) and will merge it and close this issue when nwmatcher 1.3.9 is published. Just let us know when that happens, @dperini!

**Comment by dperini** [comment] 2016-10-25 22:18
nwmatcher has been updated to version 1.3.9 with added support for escaped CSS identifiers.
There is support for both escaped IDs and escaped class names.
Includes a number of tests provided by @bellbind.
I believe this issue can be closed.

**Comment by dperini** [comment] 2016-11-26 14:30
Should this issue be closed and marked as resolved ?

**Comment by Sebmaster** [comment] 2016-11-26 14:47
Just tested this manually and since we already have #1627 open for tests I guess we don't need this anymore.

**Closed by Sebmaster** 2016-11-26 14:47 UTC

**Comment by P0oOOOo0YA** [comment] 2019-08-24 08:12
Doing jest dom manipulation test with jsdom as test environment, found out [CSS](https://developer.mozilla.org/en-US/docs/Web/API/CSS) is not defined. Seems that it is not implemented.
