### ISSUE TITLE
Anchor element properties

### ISSUE THREAD

**Issue by mlekoo** [tmpvar/jsdom#2006] opened 2017-10-02 18:33 UTC
### Basic info:
Creating an anchor element and assigning a href to it should affect in parsing the other properties but it doesn't. I'm not sure if it's a bug or missing feature - if the second one, is there a possibility that it will be implemented in the future?

- **Node.js version:** 6.9.0
- **jsdom version:** 11.3.0
- **Mocha**

### Minimal reproduction case

```js
let urlParser = document.createElement('a');
urlParser.href = "http://example.com?query=1#hash";
// "hash": "",
// "search": "",
// ... etc.
```

### How does similar code behave in browsers?
In browsers, anchor's properties are parsed properly, e.g:
https://jsbin.com/qocucihute/1/edit?js,console

Thanks,
Milosz

**Comment by domenic** [comment] 2017-10-02 18:36
This is not a minimal reproduction case, because when I put that in a file and do `node file.js`, I get an exception saying `document` is not defined.

Let me close this until such a case is provided. Please edit and ping this thread when you have done so and I will reopen.

**Closed by domenic** 2017-10-02 18:36 UTC

**Comment by kohver** [comment] 2017-10-31 09:27
Faced a similar problem when tested my code with jest. I was not able to change `link.search` prop if `link.href === '/'`.

This is because url is `null` here: https://github.com/tmpvar/jsdom/blob/2d51af302581a57ee5b9b65595f1714d669b7ea2/lib/jsdom/living/nodes/HTMLHyperlinkElementUtils-impl.js#L222-L228

because parser returned `failure` here: 
https://github.com/tmpvar/jsdom/blob/2562b8e146aefc7b7077aed9742c648dde4c9b53/lib/jsdom/living/nodes/HTMLHyperlinkElementUtils-impl.js#L282-L292

But jest uses the old jsdom now (9.12.0). Hope the next [release](https://github.com/facebook/jest/pull/4770) will fix this.

Current workaround is to set [`testURL`](http://facebook.github.io/jest/docs/en/configuration.html#testurl-string) in jest configuration.

Hope this will help someone.

**Comment by wis** [comment] 2020-06-12 21:33
here you go @domenic 
``` js
const dom = new JSDOM(`<a href="/test.php?key=abc" title="abc" class="blue">`);
let search = dom.window.document.querySelector('a').search;
console.log('search:', search);
// how/why I wanted to use HTMLAnchorElement.search
console.log('key:', new URLSearchParams(search).get("key"));
```
output:

> search: 
> key: null
> 

I love using jsdom to write scraping scripts quickly, because I get to use `querySelector|All` with CSS selectors (which I got good at making) and incrementally test in the browser's devtools.

so TIL that jsdom's (pure js) implementation of WHATWG DOM and the HTML Standard|s is not as perfect as Chromium's, which is fine, that's no easy feat, i'm just mentioning it as a future note.

**Comment by domenic** [comment] 2020-06-12 22:31
(Your example seems unrelated to the OP and would be better in a new issue.)

That's working as expected. You have no base URL for your JSDOM, so `/test.php?key=abc` does not resolve to a valid URL, and so `anchEl.search` returns the empty string. You can see the same behavior in your browser if you navigate to `about:blank` (i.e. the default URL) and run the code.
