### ISSUE TITLE
Simple example yields empty object.

### ISSUE THREAD

**Issue by tomzmtl** [tmpvar/jsdom#1891] opened 2017-06-19 19:02 UTC
Hi, I'm trying to make the simplest example work, but for some reason parsing my HTML string yields an empty object. Not getting any error or warnings.

Not exactly sure what I'm doing wrong here.

### Basic info:

- **Node.js version:** 6.9.5
- **jsdom version:** 11.0.0
- **OS:** Mac

### Reproduction case

```js
import { JSDOM } from 'jsdom';

const raw = '<!DOCTYPE html><p>Hello world</p>';
const document = new JSDOM(raw);
console.log(document);  // JSDOM {}
```

**Comment by domenic** [comment] 2017-06-19 19:20
Sorry, this uses syntax that I cannot run on my Node.js (`import`). I'll close this, but happy to reopen once you've edited it to use syntax that works on my computer so I can reproduce the issue.

**Comment by tomzmtl** [comment] 2017-06-19 20:15
@domenic Simply replace the import line by `const JSDOM = require('jsdom').JSDOM';`

**Comment by domenic** [comment] 2017-06-19 20:19
Great, OK.

It appears the problem here is that you're not logging anything interesting. You're just logging the JSDOM class (which for some reason you've called `document`).

Probably you want to log something interesting instead, e.g. `dom.window.document.outerHTML`. (Assuming you change the variable `document` to `dom`.)

**Comment by tomzmtl** [comment] 2017-06-19 20:24
Well according to the docs, instanciating a new JSDOC instance and providing raw markup is supposed to return an object with multiple properties and methods.
In my case I get an empty object, so I couldn't even access `outerHTML` because there's nothing to access.

**Comment by domenic** [comment] 2017-06-19 20:26
Yes, it has plenty of properties and methods. Please try using them. It's not an empty object, you're just not using it.

**Comment by domenic** [comment] 2017-06-19 20:26
Closing since this appears to be based on a misunderstanding of how console.log works.

**Closed by domenic** 2017-06-19 20:26 UTC

**Comment by zjroth** [comment] 2017-11-21 01:35
I have the same problem as @tomzmtl.  The issue does not seem to be a misunderstanding of how `console.log` works.

**Reproduction case**
```javascript
const JSDOM = require('jsdom').JSDOM;
const raw = '<!DOCTYPE html><p>Hello world</p>';
const dom = new JSDOM(raw);

let props = Object.getOwnPropertyNames(dom);

console.log(props.length); // 0
console.log(props);        // []
console.log(dom);          // JSDOM {}
```

**System info**
- Node.js version: 6.11.4
- jsdom version: 11.4.0
- OS: Ubuntu

**Comment by domenic** [comment] 2017-11-21 01:42
The dom object has no own properties, by design. Pick a specific property that's not working as documented before reporting a bug please. There is nothing in the readme saying that getOwnProperties returning something is part of the API contract, so it's not a good bug report.
