### ISSUE TITLE
Add { "engines" : { "node" : "> 0.12" } } to package.json for the 4.x branch

### ISSUE THREAD

**Issue by DavidBruant** [tmpvar/jsdom#1090] opened 2015-04-20 10:23 UTC
A colleague of mine (not a hardcore Node user) did `npm install jsdom --save` but he's using node 0.10, this resulted in hard-to-figure-out problems.

I believe an "engine" field on package.json would have resulted in proper warnings (and he would have read the readme more thoroughly rather than wasting time debugging his own otherwise unbuggy code).
I believe it will also help in cases where jsdom is a deep dependency.

I think `{ "engines" : { "node" : "> 0.12" } }` is the most accurate thing to write for now to trigger warning on `npm install` for all node versions, but maybe not. This issue is more the beginning of a discussion.

**Comment by Sebmaster** [comment] 2015-04-20 10:25
Duplicate of #1075.

**Closed by Sebmaster** 2015-04-20 10:25 UTC
