### ISSUE TITLE
ReferenceError: Set is not defined

### ISSUE THREAD

**Issue by jpswade** [tmpvar/jsdom#1074] opened 2015-03-26 20:51 UTC
Hi there,

I'm using the Cloud9 IDE service here:

* https://ide.c9.io/

I've created a Node.js environment and successfully run "npm install jsdom" at the console.

I've created a file called test.js with the following content:

```
var jsdom = require("jsdom");

jsdom.env(
  '<p><a class="the-link" href="https://github.com/tmpvar/jsdom">jsdom!</a></p>',
  ["http://code.jquery.com/jquery.js"],
  function (errors, window) {
    console.log("contents of a.the-link:", window.$("a.the-link").text());
  }
);
```

At runtime we get this error:

```
/home/ubuntu/workspace/node_modules/jsdom/lib/jsdom/level2/html.js:405                                                                                           
var nonInheritedTags = new Set([                                                                                                                                 
                           ^                                                                                                                                     
ReferenceError: Set is not defined                                                                                                                               
    at Object.<anonymous> (/home/ubuntu/workspace/node_modules/jsdom/lib/jsdom/level2/html.js:405:28)                                                            
    at Module._compile (module.js:456:26)                                                                                                                        
    at Object.Module._extensions..js (module.js:474:10)                                                                                                          
    at Module.load (module.js:356:32)                                                                                                                            
    at Function.Module._load (module.js:312:12)                                                                                                                  
    at Module.require (module.js:364:17)                                                                                                                         
    at require (module.js:380:17)                                                                                                                                
    at Object.<anonymous> (/home/ubuntu/workspace/node_modules/jsdom/lib/jsdom/living/index.js:8:1)                                                              
    at Module._compile (module.js:456:26)                                                                                                                        
    at Object.Module._extensions..js (module.js:474:10)                                                                                                          
```

Although I am new to node.js, I would expect this to run out of the box...

**Comment by domenic** [comment] 2015-03-27 06:04
Dupe of #1072, #1071.

**Closed by domenic** 2015-03-27 06:04 UTC

**Comment by jpswade** [comment] 2015-03-27 08:45
I'm glad to see that I am not alone in this issue. 

That being the case, I would expect error checking for io.js and a message to display if it is not found...

**Comment by domenic** [comment] 2015-03-27 08:59
That would be a mistake. We prefer feature detection to UA sniffing.
________________________________

**Comment by jpswade** [comment] 2015-03-27 09:13
The mistake is not handling the error at all.

As the documentation specifically outlines prerequisites for a particular UA, then you would expect a check for that.

If you are no longer supporting features, then that should be reflected in the documentation instead.
