### ISSUE TITLE
Stylesheet cannot be parsed if a CSS rule opens with a parentheses and closes with a curly brace

### ISSUE THREAD

**Issue by DoomTay** [tmpvar/jsdom#1878] opened 2017-06-03 18:36 UTC
### Basic info:

- **Node.js version:**  v6.10.0
- **jsdom version:** 11.0.0

### Minimal reproduction case

Assuming this is testcssdoc.html
```html
<html>
<head>
<style type="text/css">
#gooddiv {
        background-color: rgb(0,246,71);
}
#baddiv (
        background-color: rgb(173,69,71);
}
</style>
</head>
<body>
<div id="baddiv">Look at me! I'm a wierd div!</div>
<div id="gooddiv">And I'm a good div!</div>
</body>
</html>
```

then this is the main script

```js
var jsdom = require("jsdom");
var { JSDOM } = jsdom;

JSDOM.fromFile("testcssdoc.html").then(dom => {	
	console.log("It works OK");
});
```

I expect that the output would just be "It works OK", but instead I get this output:

```
Error: Could not parse CSS stylesheet
    at exports.evaluateStylesheet.e (E:\Projects\JSDom CSS Test\node_modules\jsdom\lib\jsdom\living\helpers\stylesheets.js:18:21)
    at HTMLStyleElementImpl._attach (E:\Projects\JSDom CSS Test\node_modules\jsdom\lib\jsdom\living\nodes\HTMLStyleElement-impl.js:23:5)
    at HTMLHeadElementImpl._attach (E:\Projects\JSDom CSS Test\node_modules\jsdom\lib\jsdom\living\nodes\Node-impl.js:273:15)
    at HTMLHeadElementImpl._attach (E:\Projects\JSDom CSS Test\node_modules\jsdom\lib\jsdom\living\nodes\Element-impl.js:106:11)
    at HTMLHtmlElementImpl._attach (E:\Projects\JSDom CSS Test\node_modules\jsdom\lib\jsdom\living\nodes\Node-impl.js:273:15)
    at HTMLHtmlElementImpl._attach (E:\Projects\JSDom CSS Test\node_modules\jsdom\lib\jsdom\living\nodes\Element-impl.js:106:11)
    at DocumentImpl.insertBefore (E:\Projects\JSDom CSS Test\node_modules\jsdom\lib\jsdom\living\nodes\Node-impl.js:217:22)
    at DocumentImpl.appendChild (E:\Projects\JSDom CSS Test\node_modules\jsdom\lib\jsdom\living\nodes\Node-impl.js:309:17)
    at DocumentImpl.appendChild (E:\Projects\JSDom CSS Test\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:395:18)
    at setChild (E:\Projects\JSDom CSS Test\node_modules\jsdom\lib\jsdom\browser\htmltodom.js:235:18)
#gooddiv {
        background-color: rgb(0,246,71);
}
#baddiv (
        background-color: rgb(173,69,71);
}
```

 Thankfully, the script would still continue to run.

### How does similar code behave in browsers?

#baddiv is plain, though #gooddiv shows with a green background. Also, the console outputs these CSS messages

```
Dangling combinator.  Ruleset ignored due to bad selector.  testcssdoc.html:7:8
Unexpected end of file while searching for closing } of invalid rule set.  testcssdoc.html:10
```

A real-world example of this problem occurs at https://web.archive.org/web/20170603180541/http://forums.steampowered.com/forums/forumdisplay.php?f=14. This also happens with the live web URL, http://forums.steampowered.com/forums/forumdisplay.php?f=14.

**Comment by domenic** [comment] 2017-06-03 18:54
I think this is working as intended. It just outputs errors parsing the CSS stylesheet to the virtual console, just like other errors (e.g. similar to if you `console.error()`ed inside your page). The script still runs, as you say.

**Comment by domenic** [comment] 2017-06-03 18:54
Basically the "bug report" seems to be that jsdom's console output is much longer than the browser console output, but that's not something we plan to change.

**Comment by Zirro** [comment] 2017-06-03 19:18
@DoomTay It sounds like you may want to mute the errors. You can create your own [virtual console](https://github.com/tmpvar/jsdom#virtual-consoles) and override the default.

**Comment by DoomTay** [comment] 2017-06-03 19:23
@Zirro Ooh, that helped. Thanks.

**Comment by Zirro** [comment] 2017-06-03 19:27
No problem. You can close the issue now, since the error is expected to be logged by default.

**Closed** 2017-06-03 19:32 UTC
