### ISSUE TITLE
Incompatibility with Node v7.3.0

### ISSUE THREAD

**Issue by andrepcg** [tmpvar/jsdom#1684] opened 2016-12-21 22:57 UTC
I seem to be unable to run Karma and jsdom with Node v7.3.0.

The following error occurs:

```
21 12 2016 14:34:03.540:INFO [karma]: Karma v1.3.0 server started at http://localhost:9876/
21 12 2016 14:34:03.543:INFO [launcher]: Launching browser jsdom with unlimited concurrency
21 12 2016 14:34:03.550:INFO [launcher]: Starting browser jsdom
21 12 2016 14:34:04.336:INFO [Node.js (linux; U; rv:v7.3.0) AppleWebKit/537.36 (KHTML, like Gecko)]: Connected on socket /#tduonCE02UcVqoG8AAAA with id 35304974
21 12 2016 14:34:14.343:WARN [Node.js (linux; U; rv:v7.3.0) AppleWebKit/537.36 (KHTML, like Gecko)]: Disconnected (1 times), because no message in 10000 ms.
Node.js (linux; U; rv:v7.3.0) AppleWebKit/537.36 (KHTML, like Gecko) ERROR
  Disconnected, because no message in 10000 ms.
```

**Original issue in Karma repo:** [https://github.com/karma-runner/karma/issues/2511#issuecomment-268663143](https://github.com/karma-runner/karma/issues/2511#issuecomment-268663143)

**Comment by i8-pi** [comment] 2016-12-23 10:15
You might have more luck by contributing to this https://github.com/badeball/karma-jsdom-launcher/issues/6

**Comment by domenic** [comment] 2017-01-30 05:07
Since this involves libraries besides jsdom and there has been no attempt to reproduce it using just jsdom, this is out of scope for this repository. Closing.

**Closed by domenic** 2017-01-30 05:07 UTC
