### ISSUE TITLE
document.evaluate do not use namespaceResolver function

### ISSUE THREAD

**Issue by darkowic** [tmpvar/jsdom#1880] opened 2017-06-05 08:25 UTC
### Basic info:

I use jsdom for tests with Jest. Trying to use `document.evaluate` to search in svg using xpath.

- **Node.js version: v6.10.3** 
- **jsdom version: ^11.0.0** 

### Minimal reproduction case
I have some svg and I try to search for element inside it.

This is not working. Event the nsResolver console log/throw is not called.
```js
    function nsResolver(prefix) {
      throw new Error('test');
      console.log('prefix', prefix)
      const ns = {
        'svg': 'http://www.w3.org/2000/svg'
      };
      return ns[prefix] || null;
    }

    console.log('test', document.evaluate(
      '/ns:defs/ns:pattern[@id="borderPattern"]',
      xmlDoc,
      nsResolver,
      XPathResult.ORDERED_NODE_ITERATOR_TYPE,
      null
    )[0]);
```
Console log gives undefined.

As a workaround I use `xpath` library
```js
import xpath from 'xpath';
const svgXpathSelect = xpath.useNamespaces({ ns: 'http://www.w3.org/2000/svg' });

svgXpathSelect('/ns:defs/ns:pattern[@id="borderPattern"]', xmlDoc)[0];
```
And it returns correct value.

### How does similar code behave in browsers?

Here is the specification of `evaluate` https://developer.mozilla.org/en/docs/Web/API/Document/evaluate
Before, I run those tests in browser (with karma) with this helper
```js
function svgNSResolver() {
  return 'http://www.w3.org/2000/svg';
}

function getNode(xmlDoc, path) {
  const result = xmlDoc.evaluate(path, xmlDoc, svgNSResolver, XPathResult.ORDERED_NODE_ITERATOR_TYPE, null);
  return result.iterateNext();
}
```
And works well.

**Comment by domenic** [comment] 2017-06-05 15:45
Unfortunately this is not a minimal reproduction case, as outlined in the template. So we cannot work on this issue. Closing.

**Closed by domenic** 2017-06-05 15:45 UTC

**Comment by MartijnR** [comment] 2018-06-05 20:53
Looks like namespaces in XML are not implemented: 

* https://github.com/jsdom/jsdom/blob/a6acac4e9dec4f859fff22676fb4e9eaa9139787/lib/jsdom/level3/xpath.js#L6
* https://github.com/jsdom/jsdom/blob/a6acac4e9dec4f859fff22676fb4e9eaa9139787/lib/jsdom/level3/xpath.js#L1696

**Comment by 01egen** [comment] 2019-03-29 12:21
var evaluator = new XPathEvaluator();
///////////
//  if the namespace information is embedded in the XML document ...
var resolver = evaluator.createNSResolver(xmldoc.documentElement);
// else
function resolver(prefix) {
    switch (prefix){
        case "svg": return "http://www.w3.org/2000/svg";
        default: return "http://www.w3.org/1999/xhtml"; // for example ...
    }
}
////////////
var result = evaluator.evaluate('/ns:defs/ns:pattern[@id="borderPattern"]', xmldoc.documentElement,
                 resolver, XPathResult.ORDERED_NODE_ITERATOR_TYPE, null);

result.iterateNext();
and so on ...
