### ISSUE TITLE
window object somehow gets nullified after throwing Error (?)

### ISSUE THREAD

**Issue by wojtekmaj** [tmpvar/jsdom#2056] opened 2017-11-18 19:57 UTC
### Basic info:

- **Node.js version:** v8.9.1
- **jsdom version:** v11.2.0 via Jest v21.3.0-beta.8, but reproducible on jsdom v9.x via Jest v21.2.x too

### Minimal reproduction case

Run JEST test on this repository: https://github.com/wojtekmaj/react-pdf/tree/feature/unit-testing

During my testing, I got a TypeError after my package has failed to load a file during a test scenario.

```Cannot read property 'createEvent' of undefined TypeError: Cannot read property 'createEvent' of undefined
    at Object.invokeGuardedCallbackDev (C:\react-pdf\node_modules\react-dom\cjs\react-dom.development.js:577:26)
    at invokeGuardedCallback (C:\react-pdf\node_modules\react-dom\cjs\react-dom.development.js:436:27)
    at renderRoot (C:\react-pdf\node_modules\react-dom\cjs\react-dom.development.js:10386:7)
    at performWorkOnRoot (C:\react-pdf\node_modules\react-dom\cjs\react-dom.development.js:11000:24)
    at performWork (C:\react-pdf\node_modules\react-dom\cjs\react-dom.development.js:10952:7)
    at requestWork (C:\react-pdf\node_modules\react-dom\cjs\react-dom.development.js:10861:7)
    at scheduleWorkImpl (C:\react-pdf\node_modules\react-dom\cjs\react-dom.development.js:10744:11)
    at scheduleWork (C:\react-pdf\node_modules\react-dom\cjs\react-dom.development.js:10706:12)
    at Object.enqueueSetState (C:\react-pdf\node_modules\react-dom\cjs\react-dom.development.js:6204:7)
    at Document.Object.<anonymous>.Component.setState (C:\react-pdf\node_modules\react\cjs\react.development.js:226:16)
    at Document._this.onLoadError (C:\react-pdf\src\Document.jsx:152:13)
    at <anonymous>
```

i went to `react-dom.development.js:577:26` to investigate. I found that the line failing was:

```js
var evt = document.createEvent('Event');
```

so I put some `console.log`s right before the failing line to find out what happens:

```js
if (typeof document !== 'object') {
  console.log('Something very bad happened');
  console.log(window);
  console.log(document);   
} else {
  console.log('Everything fine');
  console.log(typeof window);
  console.log(typeof document);
}
```

and the output in console was suggesting that for the first few runs, everything was working, until an error came:

```
console.log node_modules\react-dom\cjs\react-dom.development.js:582
  Everything fine
console.log node_modules\react-dom\cjs\react-dom.development.js:583
  object
console.log node_modules\react-dom\cjs\react-dom.development.js:584
  object
console.log node_modules\react-dom\cjs\react-dom.development.js:582
  Everything fine
console.log node_modules\react-dom\cjs\react-dom.development.js:583
  object
console.log node_modules\react-dom\cjs\react-dom.development.js:584
  object
console.error src\shared\util.js:96
  undefined Error {
    name: 'UnknownErrorException',
    message: undefined,
    details: 'UnknownErrorException' }
console.log node_modules\react-dom\cjs\react-dom.development.js:578
  Something very bad happened
```

interestingly, `console.log` that was supposed to be displayed right after "Something very bad happened", has thrown an error:

```
Cannot read property '_location' of null TypeError: Cannot read property '_location' of null
    at Window.get location [as location] (C:\react-pdf\node_modules\jsdom\lib\jsdom\browser\Window.js:165:79)
    at Function.getOwnPropertyDescriptor (<anonymous>)
    at formatProperty (util.js:828:23)
    at formatObject (util.js:649:17)
    at formatValue (util.js:609:18)
    at inspect (util.js:324:10)
    at format (util.js:191:12)
    at CustomConsole.log (C:\react-pdf\node_modules\jest-util\build\Console.js:38:53)
    at Object.invokeGuardedCallbackDev (C:\react-pdf\node_modules\react-dom\cjs\react-dom.development.js:579:17)
    at invokeGuardedCallback (C:\react-pdf\node_modules\react-dom\cjs\react-dom.development.js:436:27)
```

which suggests that `window` inside `Window` function suddenly got... nullified.

I can't figure out what could be going wrong here. Could you give me any hints on what could be happening? TIA!

### How does similar code behave in browsers?

n/a

**Comment by domenic** [comment] 2017-11-18 20:56
Sorry, but this didn't follow the issue template by giving a minimal reproduction case that doesn't use third-party libraries like Jest. We've seen similar problems before, all caused by Jest, and as such we cannot consider this a jsdom bug until someone provides a minimal reproduction case. So, closing.

**Closed by domenic** 2017-11-18 20:56 UTC
