### ISSUE TITLE
Boolean attrs and props not working as expected

### ISSUE THREAD

**Issue by Kflash** [tmpvar/jsdom#1452] opened 2016-04-15 06:57 UTC
It's related to this ticket https://github.com/tmpvar/jsdom/issues/1451

I tried various boolean attr combos and they didn't work. It worked with karma + mocha.

With a select multiple I tried to both hide and disable option elements. They still works and visible.

I know Edge and older ie have issues with disabled elements. But this was not done with edge.

I also tested this on windows and Linux environment. Same thing.

Phantom and jsdom I couldn't get working with latest version so didn't test. With jsdom  7.x same issues when I used phantom

**Comment by domenic** [comment] 2016-04-15 06:58
Can you provide a small minimal test case, not involving mocha but instead a 5-10 line program with only jsdom as a dependency, reproducing the problem?

**Comment by Kflash** [comment] 2016-04-16 00:50
Just do something like this

```
  var node = document.createElement('input');
 	node.setAttribute('disabled', false);
      // trigger click event
```
If you now tried to trigger a click event on it, you will notice it still works. You wrote no mocha etc. But in my case I use Sinon.spy() and this package https://www.npmjs.com/package/simulate

**Comment by Sebmaster** [comment] 2016-04-16 00:58
Seems to me like dispatching an event on a disabled element always causes the click handler to be invoked: https://jsfiddle.net/dz3h7yjn/ (with Chrome).

**Comment by Kflash** [comment] 2016-04-16 02:48
I couldn't get your jsfiddle to work, but I tried the same in Chrome, Firefox, Opera, and Edge.
In Edge and Firefox it stay disabled. In Chrome it's invoked.

If I try with Karma + jsdom - not invoked with any browser launchers I tried. 

And jsdom + mocha don't use any browsers, so I guess it shouldn't be invoked.

And to take this further...

No mouse events should ever be invoked either on disabled elements. Same in Chrome. 

If you change from 'click' to 'mousedown' it still have the same behaviour in jsdom. It get invoked.

**Comment by Kflash** [comment] 2016-04-19 23:21
What is the progress on this issue?

**Comment by domenic** [comment] 2016-04-19 23:22
I still haven't seen a minimal test case I can run with `node test.js`, so I haven't really started.

**Comment by Kflash** [comment] 2016-04-19 23:26
ok. No problem. Testem works fine

**Comment by domenic** [comment] 2016-05-01 23:46
Closing since I cannot reproduce.

**Closed by domenic** 2016-05-01 23:46 UTC
