### ISSUE TITLE
colSpan property should be a number, but in jsdom it is a string

### ISSUE THREAD

**Issue by raquo** [tmpvar/jsdom#1745] opened 2017-02-22 06:21 UTC
In jsdom, after setting colSpan property to a number (5), reading that property off the element yields a string ("5") instead of the expected number (5).

`colSpan` property is defined as a `long` in HTML4 and `unsigned long` in HTML5, not a `string`.

Browsers behave as expected, returning a number (5) for `colSpan`.  (tested in Firefox and Chrome)

JSBin for browsers: http://jsbin.com/deruqihumo/edit?html,js,console

And a similar snippet for jsdom:

    var jsdom = require('jsdom');
    jsdom.env(
        '<div id="entry"></div>',
        function (err, window) {
            var td = window.document.createElement("td")
            var div = window.document.querySelector("#entry")
            div.appendChild(td)
            td.colSpan = 5
            console.log(td.colSpan); // prints "5"
            console.log(typeof td.colSpan) // prints "string"
        }
    );

Perhaps the `String(V)` in this jsdom source code is the reason?

    set colSpan(V) {
        this.setAttribute("colspan", String(V));
    }

This is from [`jsdom/lib/jsdom/living/nodes/HTMLTableCellElement-impl.js`](https://github.com/tmpvar/jsdom/blob/a6acac4e9dec4f859fff22676fb4e9eaa9139787/lib/jsdom/living/nodes/HTMLTableCellElement-impl.js#L32)

I'm not familiar with jsdom internals... Is this just a simple bug specific to `colSpan` / `rowSpan`, or a bigger issue with how reflected properties are handled in general?

**Comment by domenic** [comment] 2017-02-22 14:24
The problem is in the getter, not the setter.

Some reflected properties are handled automatically, but not this one, since it has a default value, so the code is written manually.

**Comment by katsanva** [comment] 2017-11-24 18:00
Seems to be fixed in https://github.com/tmpvar/jsdom/commit/fe79937a303540bb3b008843554d34d3bca263ee#diff-189942eac6d38a323f9d0dae31fd35b3R29

**Closed** 2017-11-24 19:05 UTC
Labels: bug
