### ISSUE TITLE
Can't get scrollWidth from jsDOM node

### ISSUE THREAD

**Issue by bezreyhan** [tmpvar/jsdom#1192] opened 2015-08-13 02:35 UTC
I'm testing React components and one of my components tries to access the `scrollWidth` property of a jsDOM node. When I run my tests and log the result of  `scrollWidth` all I get is `undefined`, where as in the browser I get the correct value.

This is the line of code that logs undefined:
`React.findDOMNode(this.refs.sizer).scrollWidth`

However, if try to access `className` I receive the correct value.

**Comment by domenic** [comment] 2015-08-13 04:42
Basically a dupe of #1013. jsdom does not do layout, so unless you want to help write a headless CSS layout engine, this is going to be ... hard.

**Closed by domenic** 2015-08-13 04:42 UTC
