### ISSUE TITLE
async attribute is not added to script tag

### ISSUE THREAD

**Issue by artemgurzhii** [tmpvar/jsdom#1764] opened 2017-03-11 20:02 UTC
I'm using `jsdom` for testing and I'm having following function
```javascript
function loadScript(src) {
  return new Promise((resolve, reject) => {
    const script = document.createElement('script');
    script.src = src;
    script.async = true;
    document.body.appendChild(script);
  });
}
```
The problem is that `async` attribute is not added to script tag.
```javascript
const script = loadScript('helloworld.js');
script.then(value => {
  console.log(document.body.innerHTML); // <script src="helloworld.js"</script>
  console.log(script); // Promise { HTMLScriptElement { async: true } }
});
```

**Comment by Sebmaster** [comment] 2017-03-11 20:11
The async tag is not supported on script tags in jsdom.

**Comment by artemgurzhii** [comment] 2017-03-11 20:32
Some elements have attributes, which can be settled directly by setting the object property.
As `async` and `defer` for `script`, `width` and `height` for `img` and etc.
As I understand `jsdom` doesn't support any of this?

**Comment by Sebmaster** [comment] 2017-03-11 20:48
No, jsdom supports most of that. As I said, jsdom does not support the async attribute specifically.

**Comment by artemgurzhii** [comment] 2017-03-11 21:43
@Sebmaster I have added `[Reflect] attribute boolean async;` to [lib/jsdom/living/nodes/HTMLScriptElement.idl](https://github.com/tmpvar/jsdom/blob/a6acac4e9dec4f859fff22676fb4e9eaa9139787/lib/jsdom/living/nodes/HTMLScriptElement.idl) and it solved my problem. Is this correct way for doing this?

**Comment by Sebmaster** [comment] 2017-03-11 21:55
It's a start, but we'd also need to completely implement what the async attribute does to actually accept a PR. At the moment you could feature detect if async is supported with `"async" in script`, but adding the reflect without implementing it would break that, so it remains unimplemented.

**Comment by artemgurzhii** [comment] 2017-03-11 22:21
@Sebmaster Where can I find the example for `defer` implementation, so I have a starting point?

**Comment by Sebmaster** [comment] 2017-03-11 22:22
defer is similiarly not implemented.

**Comment by artemgurzhii** [comment] 2017-03-11 22:33
Can `async` get the same implementation as `defer`? They are both not implemented but using `defer` returns `<script src="helloworld.js" defer=""</script>`. And do you think that `async` needs any implementation? As it is used only to asynchronously execute the script, so parsing will not be blocked?

**Comment by domenic** [comment] 2017-03-12 19:24
Going to close this as a dupe of #1564.

The issue is that there is a lot more to these properties then just adding the appropriate HTML attributes. You also need to implement their impact on the script-loading algorithm: https://html.spec.whatwg.org/#prepare-a-script (see especially step 23)

**Closed by domenic** 2017-03-12 19:24 UTC
