### ISSUE TITLE
Changing url does not work with Jest

### ISSUE THREAD

**Issue by mockdeep** [tmpvar/jsdom#1700] opened 2017-01-09 23:18 UTC
I'm trying to change the window url in my Jest specs and it throws an error. Not sure if this is an issue with the way that Jest has configured jsdom, or a problem with jsdom. A small example:

```js
import jsdom from 'jsdom';

it('works', () => {
  jsdom.changeURL(window, 'https://example.com?foo=butts')
});
```

I run it like:

```js
$ jest --config config/jest.json spec/js/my_test.js
```

And get an error:

```
    TypeError: Cannot set property '_URL' of undefined
      
      at Object.<anonymous>.exports.changeURL (node_modules/jsdom/lib/jsdom.js:64:12)
      at Object.<anonymous> (spec/js/my_spec.js:6:45)
```

Not really much in the way of custom configuration on our part when it comes to Jest. Using `jsdom@9.9.1` and `jest@17.0.3`.

**Comment by domenic** [comment] 2017-01-09 23:27
Can you produce a repro without using Jest? It's hard for us to debug otherwise.

**Comment by Sebmaster** [comment] 2017-01-09 23:35
`jsdom.changeURL` has to be called on a document.

**Comment by mockdeep** [comment] 2017-01-09 23:43
@Sebmaster can you give me some more context? The [README says](https://github.com/tmpvar/jsdom#changing-the-url-of-an-existing-jsdom-window-instance) to pass in `window`, and when I try to pass in `window.document` I get the same error. I'll see if I can do a repro without jest.

**Comment by Sebmaster** [comment] 2017-01-09 23:47
Oh, sorry, misread the source. A repo without jest would definitely make debugging easier.

**Comment by kopax** [comment] 2017-01-11 20:25
I have the same issue. 

https://github.com/tmpvar/jsdom/blob/master/lib/jsdom/living//helpers/document-base-url.js#L42

my baseURL.path = 'blank'.

Is there a way to change that ?

**Comment by mockdeep** [comment] 2017-01-11 20:54
@kopax it looks like you may have a different issue. It tries to parse the url, so if it doesn't have a proper protocol, such as `https`, it will throw an error.

**Comment by kopax** [comment] 2017-01-11 20:59
@mockdeep , not sure, I am trying to trigger a page change using react-router within a unit test.
I have the exact same version as you and I have tried your code into my env and it did the same, helpers like `parseURLToResultingURLRecord` doesn't get called properly like a real browser..

You can also reproduce it like with this in your test: 

    window.history.pushState('page2', 'Title', '/page2.php');

**Comment by mockdeep** [comment] 2017-01-11 21:09
@kopax but what you're linking to is the step where it parses the url. For my case it does manage to parse the url just fine, it throws an error later when trying to assign it to `doc._URL`:

https://github.com/tmpvar/jsdom/blob/7ce11776ce161e8d5921a7a183585327400f786b/lib/jsdom.js#L64

**Comment by kopax** [comment] 2017-01-11 21:18
@mockdeep you're right, I landed here because you have an issue with the [document mock](https://github.com/tmpvar/jsdom/blob/7ce11776ce161e8d5921a7a183585327400f786b/lib/jsdom.js#L56).

**Comment by mockdeep** [comment] 2017-01-11 21:42
Okay, so I think I've got a representative repro for the issue I'm seeing. This raises the same error:

```js
const jsdom = require('jsdom');
const jsdomConfig = {url: 'https://test.io'};

global.document = jsdom.jsdom(undefined, jsdomConfig);

jsdom.changeURL(global.document, 'https://www.example.com');
```

Based on the [jest source](https://github.com/facebook/jest/blob/master/packages/jest-environment-jsdom/src/index.js#L29-L31), it looks like they set the markup for the dom to `undefined`. When this happens we get the `_URL` error. Not sure what to do with that information, though. Shouldn't jsdom still allow setting the url even if there is no markup?

**Comment by Sebmaster** [comment] 2017-01-11 21:45
@mockdeep Your issue is that you're passing `document` instead of window to `jsdom.changeURL`. Passing `document.defaultView` works in your case.

**Comment by mockdeep** [comment] 2017-01-11 21:47
@Sebmaster Ha, yeah, I just realized that. Same here, though it still doesn't work with jest even if I use `document.defaultView`. I'll keep digging.

**Closed** 2017-01-30 05:05 UTC
Labels: question

**Comment by orrybaram** [comment] 2017-02-02 17:30
@mockdeep Have you figured this out? I'm getting the same error.

**Comment by mockdeep** [comment] 2017-02-02 17:39
No, haven't had a chance to narrow it down. We ended up just wrapping the window url stuff in a separate helper file and mocking that with jest.

**Comment by kresli** [comment] 2017-02-23 21:08
same issue here (jest, jsdom) and no idea how to fix it `TypeError: Cannot set property '_URL' of undefined`

**Comment by i8-pi** [comment] 2017-02-25 11:17
This is caused by having more than one version of `idlUtils.implSymbol` floating around.

I think this has to do with jest running some variant of
```
jsdom.evalVMScript(sandbox, vm.Script(fs.readFileSync('utils.js')))
```
in an attempt to create a sandbox environment, but breaks stuff since `Symbol('impl') !== Symbol('impl')`. I'm not certain, though

**Comment by brotzky** [comment] 2017-03-09 18:40
I'm also getting `TypeError: Cannot set property '_URL' of undefined` when trying to set
`jsdom.changeURL(window, 'http://localhost');` for example. 

Logging out window does show the correct object

**Comment by domenic** [comment] 2017-03-09 18:41
Please for anyone experiencing this, produce some minimal (~10 line) example that uses only jsdom APIs (not Jest APIs) so we can debug it and add it to our test suite.

**Comment by brotzky** [comment] 2017-03-09 18:48
This is my configuration. Hopefully it helps. Hopefully the issue is on my end :) 

```
// setupFile.js (https://github.com/airbnb/enzyme/blob/master/docs/guides/jsdom.md)
const jsdom = require('jsdom').jsdom;

const documentHTML = '<!doctype html><html><body><div id="root"></div></body></html>';
global.document = jsdom(documentHTML);
global.window = document.defaultView;

Object.keys(document.defaultView).forEach((property) => {
  if (typeof global[property] === 'undefined') {
    global[property] = document.defaultView[property];
  }
});

global.navigator = {
  userAgent: 'node.js'
};
```


```
// apit.test.js
import { baseUrl } from '../api';
import jsdom from 'jsdom';

describe('[Utility] api', () => {
  describe('baseUrl', () => {
    console.log(window) // logs out window
    jsdom.changeURL(window, 'https://localhost:9001');

    it('should return a relative URL if it\'s not local', () => {
      expect(baseUrl).toEqual('/v1');
    });
  });
});

**Comment by domenic** [comment] 2017-03-09 18:49
Can you produce a version which does not add properties to the global object? That isn't a supported configuration. See https://github.com/tmpvar/jsdom/wiki/Don't-stuff-jsdom-globals-onto-the-Node-global

**Comment by domenic** [comment] 2017-03-09 18:50
Also, a version which doesn't depend on Mocha.

**Comment by domenic** [comment] 2017-03-09 18:50
Or on syntax which doesn't compile in my Node.js.

**Comment by brotzky** [comment] 2017-03-09 18:57
thanks for the links!

**Comment by jozsi** [comment] 2017-03-20 11:05
I am also having a similar issue regarding `history` (initializing a React app w/ react-router; ran via jest):
```
(node:1831) TypeError: Cannot read property '_history' of null
    at Window.get history [as history] (/Users/jozsi/Dev/wealthor/node_modules/jsdom/lib/jsdom/browser/Window.js:151:79)
    at /Users/jozsi/Dev/wealthor/node_modules/history/lib/BrowserProtocol.js:93:18
    at updateLocation (/Users/jozsi/Dev/wealthor/node_modules/history/lib/BrowserProtocol.js:82:3)
    at replaceLocation (/Users/jozsi/Dev/wealthor/node_modules/history/lib/BrowserProtocol.js:92:10)
    at /Users/jozsi/Dev/wealthor/node_modules/history/lib/createHistory.js:119:15
    at /Users/jozsi/Dev/wealthor/node_modules/history/lib/createHistory.js:90:9
    at next (/Users/jozsi/Dev/wealthor/node_modules/history/lib/AsyncUtils.js:51:7)
    at loopAsync (/Users/jozsi/Dev/wealthor/node_modules/history/lib/AsyncUtils.js:55:3)
    at confirmTransitionTo (/Users/jozsi/Dev/wealthor/node_modules/history/lib/createHistory.js:80:31)
    at transitionTo (/Users/jozsi/Dev/wealthor/node_modules/history/lib/createHistory.js:100:5)
```

```js
    get history() {
      return idlUtils.wrapperForImpl(idlUtils.implForWrapper(window._document)._history);
    },
```

I'll try to allocate some time in setting up a test repo, without jest.

**Comment by okovpashko** [comment] 2017-05-02 08:37
It really looks like there are two different `idlUtils.implSymbol` as @i8-pi said. 
I've added a simple logging inside `changeURL` before [this line](https://github.com/tmpvar/jsdom/blob/master/lib/old-api.js#L56):
```
console.warn('are impl symbols equal', idlUtils.implSymbol === Object.getOwnPropertySymbols(window._document)[0]);
```
run a test that calls `changeURL` and got 
```
are impl symbols equal false
```
in console. 
Note that `Object.getOwnPropertySymbols(window._document)` returns only one symbol `Symbol(impl)` so I compare symbol contained in `window._document` with one that is used as a key for getting document instance and they don't match.
So it's probably not a jsdom issue and we should find the resolution in Jest repo.

**Comment by webdevbyjoss** [comment] 2017-11-03 12:56
Getting the similar failure under Jest with HashRouter + jsdom

```
TypeError: Cannot read property '_history' of null
    at Window.get history [as history] (.../node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/browser/Window.js:151:79)
    at createHashHistory (.../node_modules/history/createHashHistory.js:71:29)
    at new HashRouter (.../node_modules/react-router-dom/HashRouter.js:48:195)
    at ..../node_modules/react-dom/lib/ReactCompositeComponent.js:292:18
    at measureLifeCyclePerf (.../node_modules/react-dom/lib/ReactCompositeComponent.js:73:12)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (.../node_modules/react-dom/lib/ReactCompositeComponent.js:291:16)
    at ReactCompositeComponentWrapper._constructComponent (.../node_modules/react-dom/lib/ReactCompositeComponent.js:282:19)
    at ReactCompositeComponentWrapper.mountComponent (.../node_modules/react-dom/lib/ReactCompositeComponent.js:185:21)
    at Object.mountComponent (.../node_modules/react-dom/lib/ReactReconciler.js:43:35)
    at ReactCompositeComponentWrapper.performInitialMount (.../node_modules/react-dom/lib/ReactCompositeComponent.js:368:34)
```

**Comment by jeffryang24** [comment] 2020-03-02 12:22
> Getting the similar failure under Jest with HashRouter + jsdom
> 
> ```
> TypeError: Cannot read property '_history' of null
>     at Window.get history [as history] (.../node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/browser/Window.js:151:79)
>     at createHashHistory (.../node_modules/history/createHashHistory.js:71:29)
>     at new HashRouter (.../node_modules/react-router-dom/HashRouter.js:48:195)
>     at ..../node_modules/react-dom/lib/ReactCompositeComponent.js:292:18
>     at measureLifeCyclePerf (.../node_modules/react-dom/lib/ReactCompositeComponent.js:73:12)
>     at ReactCompositeComponentWrapper._constructComponentWithoutOwner (.../node_modules/react-dom/lib/ReactCompositeComponent.js:291:16)
>     at ReactCompositeComponentWrapper._constructComponent (.../node_modules/react-dom/lib/ReactCompositeComponent.js:282:19)
>     at ReactCompositeComponentWrapper.mountComponent (.../node_modules/react-dom/lib/ReactCompositeComponent.js:185:21)
>     at Object.mountComponent (.../node_modules/react-dom/lib/ReactReconciler.js:43:35)
>     at ReactCompositeComponentWrapper.performInitialMount (.../node_modules/react-dom/lib/ReactCompositeComponent.js:368:34)
> ```

Same issue with next-router...
