### ISSUE TITLE
TypeError: Cannot read property 'cssRules' of undefined

### ISSUE THREAD

**Issue by kaiyoma** [tmpvar/jsdom#2122] opened 2018-01-23 01:10 UTC
**Node.js version:** 8.9.0
**jsdom version:** 11.6.0

After upgrading from version 11.5.1, I'm getting an error when running my tests:

```
C:\Users\Foo\Work\foo\node_modules\domkit\insertRule.js:15
  var index = (extraSheet.cssRules || extraSheet.rules).length;
                          ^

TypeError: Cannot read property 'cssRules' of undefined
    at module.exports (C:\Users\Foo\Work\foo\node_modules\domkit\insertRule.js:15:27)
    at module.exports (C:\Users\Foo\Work\foo\node_modules\domkit\insertKeyframesRule.js:27:3)
    at Object.<anonymous> (C:\Users\Foo\Work\foo\node_modules\halogenium\src\BeatLoader.jsx:20:23)
    at Module._compile (module.js:635:30)
    at Module._extensions..js (module.js:646:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\Foo\Work\foo\node_modules\babel-
register\lib\node.js:152:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Foo\Work\foo\node_modules\halogenium\lib\Halogenium.js:8:20)
    at Module._compile (module.js:635:30)
    at Module._extensions..js (module.js:646:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\Foo\Work\foo\node_modules\babel-
register\lib\node.js:152:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:/Users/Foo/Work/foo/src/components/LoadingIndicator/index.js:2:1)
    at Module._compile (module.js:635:30)
    at loader (C:\Users\Foo\Work\foo\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\Foo\Work\foo\node_modules\babel-
register\lib\node.js:154:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:/Users/Foo/Work/foo/src/components/DataGrid/index.js:8:1)
    at Module._compile (module.js:635:30)
    at loader (C:\Users\Foo\Work\foo\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\Foo\Work\foo\node_modules\babel-
register\lib\node.js:154:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:/Users/Foo/Work/foo/src/components/DataGrid/__test__/index.spec.js:11:1)
    at Module._compile (module.js:635:30)
    at loader (C:\Users\Foo\Work\foo\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\Foo\Work\foo\node_modules\babel-
register\lib\node.js:154:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at C:\Users\Foo\Work\foo\node_modules\mocha\lib\mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\Users\Foo\Work\foo\node_modules\mocha\lib\mocha.js:228:14)
    at Mocha.run (C:\Users\Foo\Work\foo\node_modules\mocha\lib\mocha.js:536:10)
    at Object.<anonymous> (C:\Users\Foo\Work\foo\node_modules\mocha\bin\_mocha:582:18)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
error Command failed with exit code 1.
```

**Comment by TimothyGu** [comment] 2018-01-23 01:23
This issue doesn't really offer a way to reproduce the problem, and it uses several third-party modules like Mocha, Babel, Halogenium, and domkit. 

The latest release has a lot of commits, and it would be really great if you could produce a reduced reproduction case that follows our [ISSUE\_TEMPLATE](https://github.com/tmpvar/jsdom/blob/master/.github/ISSUE_TEMPLATE.md) (just jsdom, nothing else), as we've seen in many cases that the issue turns out to be elsewhere than jsdom when there is such a big dependence tree.

**Comment by TimothyGu** [comment] 2018-01-23 01:30
Reduced test case:

```js
const { JSDOM } = require('jsdom');

const dom = new JSDOM('');

const style = dom.window.document.createElement('style');

style.sheet;
  // 11.5.1: CSSStyleSheet
  // 11.6.0: null
  // Chrome: null

dom.window.document.head.appendChild(style);

style.sheet;
  // 11.5.1: CSSStyleSheet
  // 11.6.0: null
  // Chrome: CSSStyleSheet
```

So, it seems like we fixed one bug but exposed another...

**Comment by TimothyGu** [comment] 2018-01-23 01:55
Another repro:

```js
const { JSDOM } = require('jsdom');

const dom = new JSDOM('<style></style>');
  // On the other hand, '<style> </style>' (note the space in between) works just fine.

dom.window.document.head.children[0].sheet;
  // 11.6.0: null (should be a CSSStyleSheet)
```

Specifically, the bug seems to be this way because we are only implementing the third condition in [the conditions to update a `style` block](https://html.spec.whatwg.org/multipage/semantics.html#the-style-element:update-a-style-block):

> * The element is popped off the stack of open elements of an HTML parser or XML parser.
> * The element is not on the stack of open elements of an HTML parser or XML parser, and it becomes connected or disconnected.
> * The element's child text content change steps run.

https://github.com/tmpvar/jsdom/blob/dc150a182db8cb17a682e21073c43efd9e0ad2a0/lib/jsdom/living/nodes/HTMLStyleElement-impl.js#L14-L21

**Comment by kaiyoma** [comment] 2018-01-23 19:35
Thanks for coming up with some test cases! Sorry I couldn't be more helpful there. We use `jsdom` in our testing, but we don't use it directly, so I actually have no idea how it works or how to interface with it. We set it up according to the instructions [here](https://github.com/airbnb/enzyme/blob/master/docs/guides/jsdom.md) and then test our React components.

**Comment by TimothyGu** [comment] 2018-01-24 01:40
Unfortunately this issue is more complex than I previously imagined. Both the old and new implementations have certain bugs.

Bugs that exist in both implementations:

* `style` elements that are not connected (or got disconnected) but with inner text still have a non-null `sheet` (this `sheet` is also in `document.styleSheets` when it shouldn't be)

   ```js
   dom = new (require("jsdom").JSDOM)("<style>abc {}</style>");

   style = dom.window.document.head.children[0];
   dom.window.document.head.children.removeChild(style);
   style.sheet; // CSSStyleSheet {} // should be null

   style = dom.window.document.createElement("style");
   style.innerHTML = `a {}`;
   style.sheet; // CSSStyleSheet {} // should be null
   ```

* `@import`s in `style` don't work (this is an issue in NEW API, as the default `FetchExternalResources` does not have `"style"`, only `"link"`)

   ```js
   dom = new (require("jsdom").JSDOM)(`<style>@import "https://www.w3.org/StyleSheets/TR/2016/base.css";</style>`, { resources: "usable" });
   // wait
   dom.window.document.head.children[0].sheet.cssRules[0].styleSheet.cssRules; // [] // should be filled with rules
   ```

* `link` with `@import` has `sheet` pointed to the imported sheet

   ```js
   // Base64 encoding of @import "https://www.w3.org/StyleSheets/TR/2016/base.css";
   dom = new (require(".").JSDOM)(`<link rel=stylesheet href="data:text/css;base64,QGltcG9ydCAiaHR0cHM6Ly93d3cudzMub3JnL1N0eWxlU2hlZXRzL1RSLzIwMTYvYmFzZS5jc3MiOw==">`, { resources: "usable" });
   // wait
   dom.window.document.head.children[0].sheet.cssRules.length; // 170 // should be 1
   ```

* `link` can get into wrong order in `document.styleSheets`

   ```js
   dom = new (require("jsdom").JSDOM)(`<link rel=stylesheet href="https://www.w3.org/StyleSheets/TR/2016/base.css"><style> </style>`, { resources: "usable" });
   dom.window.document.styleSheets[0] === dom.window.document.head.children[0].sheet; // false // should be true
   ```

Old implementation's bugs that the new implementation doesn't have:

* Updating a `style` element's text doesn't update the parsed stylesheet:

   ```js
   dom = new (require("jsdom").JSDOM)("<style>invalid {</style>");
   dom.window.document.head.children[0].sheet.cssRules; // []
   dom.window.document.head.children[0].innerHTML = "a {}";
   dom.window.document.head.children[0].sheet.cssRules; // [] // should be [ CSSStyleRule {} ]
   ```

* `style` and `link` elements that are not connected with empty content still have a non-null `sheet`

   ```js
   dom = new (require("jsdom").JSDOM)("");
   dom.window.document.createElement("style").sheet; // CSSStyleSheet {} // should be null
   dom.window.document.createElement("link").sheet; // CSSStyleSheet {} // should be null
   ```

* `link` elements whose `rel` is not `stylesheet` still have a non-null `sheet`

   ```js
   dom = new (require("jsdom").JSDOM)(`<link href="https://www.w3.org/StyleSheets/TR/2016/base.css">`, { resources: "usable" });
   dom.window.document.head.children[0].sheet; // CSSStyleSheet {} // should be null
   ```

Bugs in the new implementation that don't exist in the old implementation:

* Empty `style` doesn't have `sheet` even when connected (OP)

   ```js
   dom = new (require("jsdom").JSDOM)("<style></style>");
   dom.window.document.head.children[0].sheet; // null // should be CSSStyleSheet {}

   style = dom.window.document.createElement("style");
   dom.window.document.head.appendChild(style);
   style.sheet; // null // should be CSSStyleSheet {}
   ```

**Comment by domenic** [comment] 2018-01-24 06:30
I have a fix for this; currently finding out if it breaks other tests.

I plan to tackle this and #2123 as regressions, and open a separate issue for the preexisting problems. The code here is so bad, as @TimothyGu discovered... import processing in particular is really messed up.

**Closed** 2018-01-25 00:36 UTC
