### ISSUE TITLE
SVG clipPath element incorrectly lowercased

### ISSUE THREAD

**Issue by benwiley4000** [tmpvar/jsdom#1646] opened 2016-11-06 07:51 UTC
I'm working on [server-side rendering for the Metrics Graphics library](https://github.com/mozilla/metrics-graphics/pull/723) which makes use of jsdom. For the SVG I'm rendering a couple things come out differently on the server vs client:

* The [SVG clipPath element](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/clipPath) is lowercased.
* The server markup contains an empty class attribute on the `svg` tag while the client markup does not.

I believe at least the first of these two issues is jsdom's doing. Unsure about the second.

**Comment by domenic** [comment] 2016-11-06 15:09
The first is a dupe of https://github.com/tmpvar/jsdom/issues/620 which is tough to fix. For the second, please open a separate issue with a small (10-20 lines) standalone repro case.

**Closed by domenic** 2016-11-06 15:09 UTC

**Comment by benwiley4000** [comment] 2016-11-06 16:35
Thank you!
