### ISSUE TITLE
Setting window.innerWidth

### ISSUE THREAD

**Issue by okeydoke** [tmpvar/jsdom#1714] opened 2017-01-24 19:15 UTC
Hey there,
I've been trying to change the `window.innerWidth` value but not having any luck.
```js
    Object.defineProperty(window, 'innerWidth', {
      configurable: true,
      writable: true,
      value: 500
    });
```
That approach doesn't seem to work, so is there another way or have I missed something?

Thanks

**Comment by domenic** [comment] 2017-01-24 19:20
What Node.js version? There was a regression in v7.2.0 I believe that affects scenarios like this.

**Comment by okeydoke** [comment] 2017-01-24 19:21
Thanks for the quick reply, I'm using `v7.4.0`

**Comment by domenic** [comment] 2017-01-24 19:22
It looks like this will be fixed by https://github.com/nodejs/node/pull/10920 so hopefully next Node.js release.

**Comment by okeydoke** [comment] 2017-01-24 19:23
Ah ok thanks!

**Closed** 2017-01-24 20:06 UTC
