### ISSUE TITLE
How to access an element dataset?

### ISSUE THREAD

**Issue by joetidee** [tmpvar/jsdom#1747] opened 2017-02-27 14:33 UTC
I am using jsdom to create the `window.document` object and pass it into a function that is being tested. However, after creating an new element I cannot set the `dataset` property:

Here is my function:
```
var my = function(document){
    var item = document.createElement('a');
    gridItem.tabIndex = 1;
    gridItem.dataset.num = 1;
};
```

The error I get when running my test is:

> TypeError: Cannot set property 'num' of undefined

**Comment by Sebmaster** [comment] 2017-02-27 14:39
Duplicate of #961.

**Closed by Sebmaster** 2017-02-27 14:39 UTC
