### ISSUE TITLE
inserting script tag with inline code does not work.

### ISSUE THREAD

**Issue by izyware** [tmpvar/jsdom#1727] opened 2017-02-06 17:15 UTC
the framework does not execute the code that gets brought in using the <script> tag. i.e. 

`
		var script = document.createElement('script');  
		script.type = 'text/javascript';    
		code = 'console.log("script insert");';
          try {
            // doesn't work on ie...
            script.appendChild(document.createTextNode(code));      
          } catch(e) {
            // IE has funky script nodes
            script.text = code;
          } 
 		var s = document.getElementsByTagName('script')[0]; 
		s.parentNode.insertBefore(script, s); 
`

what I am doing wrong here?

**Comment by unional** [comment] 2017-02-18 22:13
Suggest to make your sample code as code block:

```js
var script = document.createElement('script');
script.type = 'text/javascript';
var code = 'console.log("script insert");';
try { // doesn't work on ie... 
  script.appendChild(document.createTextNode(code));
} catch(e) { // IE has funky script nodes
  script.text = code;
}
var s = document.getElementsByTagName('script')[0];
s.parentNode.insertBefore(script, s);
```

You can also get syntax highlighting out of it.

**Comment by izyware** [comment] 2017-02-20 18:40
ah ok, thanks for the tip. so do you know the reason why the code is not working?

**Comment by domenic** [comment] 2017-04-29 13:45
Sorry we never got around to this.

I'll close this, since it doesn't contain enough information to reproduce the issue (e.g., it doesn't seem to use jsdom at all). Please feel free to open a new issue with complete information if you're still having the problem. If you do so, I'd encourage you to use the new API documented in the readme, and carefully read the section https://github.com/tmpvar/jsdom#executing-scripts

**Closed by domenic** 2017-04-29 13:45 UTC
