### ISSUE TITLE
window.open must be set twice in order to change in strict mode

### ISSUE THREAD

**Issue by AgentME** [tmpvar/jsdom#1703] opened 2017-01-14 02:36 UTC
I'm seeing something strange with jsdom. Here's the code, and the console.log output is in comments.

```js
'use strict';

const jsdom = require('jsdom');
const doc = jsdom.jsdom('');
const window = doc.defaultView;
const other = 123;

console.log(window.open === other); // false
window.open = other;
console.log(window.open === other); // false
window.open = other;
console.log(window.open === other); // true
```

That second false is surprising and isn't consistent with browsers.

(I'm working on a browser extension which interacts heavily with a web page, and wraps `window.open` so it can access the parameters passed to it. I have an automated test of this code using jsdom.)

The issue only happens in strict mode. If you remove the `'use strict';` part, then the second console.log outputs true instead.

**Comment by vsemozhetbyt** [comment] 2017-01-14 09:00
FWIW:
```
// Node.js 4.7.2 (v8 4.5.103.43)
false
true
true

// Node.js 5.12.0 (v8 4.6.85.32)
false
true
true

// Node.js 6.9.4 (v8 5.1.281.89)
false
true
true

// Node.js 7.4.0 (v8 5.4.500.45)
false
false
true

// Node.js 8.0.0-nightly201701127f20c8a3d4 (v8 5.4.500.46)
false
false
true
```

**Comment by vsemozhetbyt** [comment] 2017-01-14 09:19
`Object.defineProperty` works the same. `window.open` is not getter/setter. It seems no `Proxy` involved.

**Comment by domenic** [comment] 2017-01-14 14:57
Nice find. Can reproduce with vanilla vm, so this is a Node bug:

```js
"use strict";
const vm = require("vm");
const ctx = vm.createContext({ open() { } });
const window = vm.runInContext("this", ctx);
const other = 123;

console.log(window.open === other);
window.open = other;
console.log(window.open === other);
window.open = other;
console.log(window.open === other);
```

**Comment by domenic** [comment] 2017-01-30 05:06
Closing since we can't do anything about it in jsdom, but hopefully a new Node release will happen soon with the fix.

**Closed by domenic** 2017-01-30 05:06 UTC
