### ISSUE TITLE
Setting env configuration with raw cookie value via attribute "cookie" appears to be deprecated.

### ISSUE THREAD

**Issue by danetb** [tmpvar/jsdom#1323] opened 2015-12-19 21:05 UTC
Tried creating env with a custom configuration, like such, but the cookie header is absent from the resulting http request.

```
jsdom.env({
    url: 'http://localhost',
    cookie: 'key=value; expires=Wed, Sep 21 2011 12:00:00 GMT; path=/',
    done: function (err1, window1) {
        //...
    }
});
```

**Comment by domenic** [comment] 2015-12-20 16:00
Confirmed. This is actually unfortunately hard to fix as all our cookie-related logic is confusingly wedged in _after_ the initial request. I can continue giving it a try...

**Comment by kedadi** [comment] 2016-05-19 18:10
looks like the way to go is through headers:

```
jsdom.env({
    url: 'http://localhost',
    headers: {
      cookie: 'key=value; expires=Wed, Sep 21 2011 12:00:00 GMT; path=/',
    }
    done: function (err1, window1) {
        //...
    }
});
```

**Comment by domenic** [comment] 2017-05-21 23:36
Going to close this as the new API provides a much better mechanism for adding cookies, and the old API has a workaround as documented above.

**Closed by domenic** 2017-05-21 23:36 UTC
Labels: bug, fixed in newapi
